### ISSUE TITLE
Logo Design For KeyMapper

### ISSUE THREAD

**Issue by zularizal** [sds100/KeyMapper#1]
Hello @sds100 ,I am a graphic designer, I want to help others in graphic design.

After I review your project, your app is very good. But I think your icon is irrelevant to your application. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by TheMadHau5** [comment]
why was this closed?

**Comment by sds100** [comment]
I can't remember. 😂 I had no idea this was the first issue. I'm not sure why I closed it.
