### ISSUE TITLE
Better Android TV support

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#121]
- [ ] Don't require DND permission for volume related actions to work.
- [ ] Use TV optismised layout.
- [ ] Advertise in descriptions that it is optimised for Android TV.
- [ ] fix button to find accessibility service and write settings permission page. 
- [ ] On homescreen, just have a list on the side with the config key maps activity on the side.
- [ ] test that the app can be navigated with just the dpad.  
- [ ] add app to Android TV Play Store.

**Comment by hoshsadiq** [comment]
Also need to add a leanback launcher icon.

**Comment by bahusoid** [comment]
Currently there is no way to select  actions without mouse. Only switch between action categories are currently supported (App/App Shortcut/...)
Would be cool if pressing Down when in categories would move selection to list of actions. And pressing Up on first action selection should move back list of categories.
Page UP/Down and Channel Up/Down should work as next/prev page in list of actions.

**Comment by sds100** [comment]
Thank you for pointing out the problem. I'll fix it when I get around to adding Android TV support.

**Comment by sds100** [comment]
split this up into multiple issues
