### ISSUE TITLE
Add option to use root method to input a keyevent instead of having to use the input method.

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#157]

**Comment by germ** [comment]
Is kind of passthrough even possible?

**Comment by sds100** [comment]
Yeah, you can input keyevents through the Android shell through ADB or as superuser on the device.

**Comment by germ** [comment]
Damn. Was hoping for a non-root solution maintain the stock BlackBerry keyboard. They have firmware integrity checks and all that good stuff that you can't disable. Great for business, bad for hacking :

Unless you can access adb pragmaticly.

Keep up the great work!

**Comment by sds100** [comment]
Yeah, there isn't a non-root way for clear security reasons.

I'll keep working on the app but it will be at a slower pace since I have more work to do for my studies. I hope to the app out of beta soon once it is very stable. The main2 things I want to work on before I take it out of beta is a tutorial when the user first opens the app and to be able to collapse and expand the card on top of the homescreen.

Thanks for the feedback! 😊

**Comment by sds100** [comment]
input keyevents through the shell is much slower.
