### ISSUE TITLE
Caps lock key still caps locks when remapped

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#169]
- [ ] if a compatible IME is chosen, consume all keyevents with the caps lock meta state and resend them without the caps lock flag with the selected Key Mapper IME.
- [ ] show dialog when creating a caps lock trigger that they need to be using the Key Mapper compatible IME they selected for the remap to work.

**Comment by sds100** [comment]
can't be fixed by consuming the up event since all other keys have the CAPS_LOCK meta state still.

**Comment by robsmith11** [comment]
Have you found a way to remap caps lock?

The only solution that I've found for a non-rooted phone is "External Keyboard Helper".  I don't mind paying for an app, but am uncomfortable with a closed source app intercepting all of my key strokes..
https://play.google.com/store/apps/details?id=com.apedroid.hwkeyboardhelperdemo&hl=en_US

**Comment by sds100** [comment]
i think i've just come up with an idea.... let me test it then I'll leave a comment.

**Comment by sds100** [comment]
just realised that method wouldnt work

**Comment by robsmith11** [comment]
FYI, I ended up using this custom keyboard layout out that swaps Ctrl and Caps Lock:
https://play.google.com/store/apps/details?id=jp.kcm.thumbctrl.en.layout&hl=en_US

**Comment by sds100** [comment]
oh, okay. ill look into how they do it. Thanks for letting me know.

**Comment by sds100** [comment]
will be fixed in the next big release since I'm changing how keymaps are detected.

**Comment by yesco** [comment]
So, just a note - it's still not working.

I just got the wrong BOW keyboard where they swapped CTRL and FN key, I'm not sure where this plague originated, but there is no way I can twist my fingers to a control key which is below letter Z... LOL

So, the FN key seems to be totally not "a key", but only happens in hardware  and only inside the keyboard, if I understand it correctly.

In keyboard mapper, the CAPS key can be assigned and the target can be CTRL key, or the left control key but it performs no such action. Actually, if enabling toast messages it says it's performing actions, but it doesn't work in practice as CTRL-L using CAPS-L doesn't work. The event is also triggered continously when holding the key down, indicating it doesn't work as a "shift"/ctrl/alt modifier key.

Not sure why this was marked as resolved.

Anyway, all in all. I love this program!

Anyway, as a curious mention,

**Comment by sds100** [comment]
Yeah, you are right about the Fn key. I'm not sure why I closed this. 🤔 The only way I could think of making it work is by making key Mapper consume all key events with the caps lock flag and then inputting the keys with the Key Mapper keyboard without the caps lock flag. I will show a dialog when the Caps Lock key is remapped letting the user know that they have to have the Key Mapper keyboard chosen for it to stop being a Caps Lock.

**Comment by sds100** [comment]
fixed. used the same method as https://play.google.com/store/apps/details?id=jp.kcm.thumbctrl.en.layout&hl=en_US
