### ISSUE TITLE
Make clicking Stop recording button optional

### ISSUE THREAD

**Issue by bahusoid** [sds100/KeyMapper#184]
Please do not clear recorded actions if Stop button is not clicked. It's not very convenient for non-touch interfaces to click this button.

**Comment by sds100** [comment]
Would adding the recorder trigger after 5 seconds instead of clearing it be fine? Or can you think of a better way.

**Comment by bahusoid** [comment]
Yes. Just save what was recorded as if Stop button is clicked.

**Comment by sds100** [comment]
Okay. It's a quick fix and been on the to-do list for a while so I'll try to implement it this weekend. Thanks.

**Comment by bahusoid** [comment]
Cool! Thanks.

**Comment by sds100** [comment]
I've implemented it!

**Comment by bahusoid** [comment]
Thanks! It works :)
