### ISSUE TITLE
Support Multi-Key Actions

### ISSUE THREAD

**Issue by robsmith11** [sds100/KeyMapper#186]
On my unrooted Huawei Mate 20 X with Android P, I'd like to stop Android from capturing "Ctrl Space".  By default, it is mapped to "change keyboard layout", but I'd instead like it passed directly to apps like Termux.

With KeyMapper, I am able to successfully capture "Ctrl Space" as a trigger and remap it to any available action, but I don't see the option for a multi-key action (reproducing Ctrl Space).  Is this possible?

**Comment by sds100** [comment]
No, it isn't possible yet. That is a good idea. For example, would you want to to input a Ctrl key then the Space key? It would only work if you have the key mapper input method selected.

**Comment by robsmith11** [comment]
Yes, exactly.

It is a little annoying to have to switch input methods when I want to use my bluetooth keyboard, but I guess it's worth it to be able to properly use terminal apps like Emacs. :)  I don't understand why (unrooted) Android can't allow for separate default input methods for physical and virtual keyboards.. I obviously still want to use SwiftKey when I'm not using a bluetooth keyboard.

**Comment by sds100** [comment]
Yeah, I totally agree, which is why I tried to make it easier by adding an option to the app to automatically switch the input method when a bluetooth device is connected/disconnected. Unfortunately you need to be rooted for it to work on Android 8.1+. I always root my devices so isn't a problem for me but for most people it is.

**Comment by sds100** [comment]
The "problem" exists so they can keep Android more secure. Otherwise someone could easily intercept all inputs and input stuff into your device.

**Comment by sds100** [comment]
In 2.0 plan issue
