### ISSUE TITLE
Stops working after a few hours

### ISSUE THREAD

**Issue by robsmith11** [sds100/KeyMapper#188]
Unfortunately, I'm not sure how to debug this..

I have a few keys mapped to launch apps.  They work great for a while, but will then suddenly stop working (all remapped keys) until I go into the Android Accessibility menu and disable and then reenable KeyMapper.

On Android 9 with Huawei Mate 20 X.

**Comment by sds100** [comment]
Have you disabled battery optimisation for the app? People have had that problem before. Unless you see a "Key Mapper has stopped working" message

**Comment by sds100** [comment]
In the next release you'll be able to see when the accessibility service is started/stopped in the Log activity.

**Comment by sds100** [comment]
can you confirm whether this is still a problem?

**Comment by robsmith11** [comment]
Yes, I've disabled all of the battery optimizations that I could, even enabled performance mode, but it's possible that Huawei is hiding some things.

The mappings still stop working 2-3 times per day.

**Comment by sds100** [comment]
Can you enable logging in the app then the next time it stops working,look whether it says the accessibility stopped working. Then send me the log. Thanks.

**Comment by sds100** [comment]
The log could be quite verbose since it records whenever you press physical buttons on your device.

**Comment by sds100** [comment]
im going to try something in my app then send you an apk to install so i can see if it helps figuring out what is going on...

**Comment by robsmith11** [comment]
I didn't realize the logging was already added to the current release.  I was still waiting for the next one. ;)

I've turned it on and will report back with anything that's logged after it stops working.

**Comment by sds100** [comment]
Okay. Thanks.

**Comment by robsmith11** [comment]
Nothing interesting in the logs.. when it stops working, nothing further is written to the log until I restart the accessibility service.

I'm thinking that Android is killing the service to free memory rather than save battery because it usually happens after using a large number of other apps.  I have 6GB of RAM, but I think it's pretty aggressive about killing background processes.  Not sure how to protect KeyMapper from being killed..

Example from log:

```
Down Key Event
[May 26, 2019 13:27:19]: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_ALT_RIGHT, scanCode=100, metaState=META_ALT_ON|META_ALT_RIGHT_ON, flags=0x8, hwFlags=0x0, repeatCount=0, eventTime=294392188, downTime=294392188, deviceId=24, source=0x101 }

Performed Action
[May 26, 2019 13:27:19]: APP org.mozilla.firefox_beta []

Consumed Down
[May 26, 2019 13:27:19]: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_ALT_RIGHT, scanCode=100, metaState=META_ALT_ON|META_ALT_RIGHT_ON, flags=0x8, hwFlags=0x0, repeatCount=0, eventTime=294392188, downTime=294392188, deviceId=24, source=0x101 }

Up Key Event
[May 26, 2019 13:27:19]: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_ALT_RIGHT, scanCode=100, metaState=0, flags=0x8, hwFlags=0x1, repeatCount=0, eventTime=294392340, downTime=294392188, deviceId=24, source=0x101 }
```

**Comment by sds100** [comment]
Yeah. That looks like what it is. Does your phone have a setting to disable battery/memory optimisations? Not the per-app setting

**Comment by sds100** [comment]
Does this help? https://phandroid.com/2017/02/02/huawei-honor-emui-first-thing/

**Comment by robsmith11** [comment]
Ok, I may have solved it.  I found a 2nd set of battery optimizaiton settings by searching for "Special Access".  I'm not sure how to even get there from the main settings menu.. Hopefully this change fixes it.  Thanks for your help!

**Comment by sds100** [comment]
That's great! If you need anymore help, just pop me an email.

**Comment by robsmith11** [comment]
Unfortunately, it seems that wasn't a complete fix.  The accessibility service still stops 1-2 times a day.  I guess Huawei must be doing something with background services that isn't configurable.

But it's a minor inconvenience. KeyMapper is still makes my phone way better :)

**Comment by sds100** [comment]
Aw, that sucks. It is ashame OEMs are managing the memory more aggressively to "improve battery life" and so they can advertise the phone to have a longer battery life. I guess it is fine for "normal" users since they don't customise their phone much but for power-users it isn't useful. They should always provide an option to toggle it (like oneplus) since if you do want very good battery life for whatever reason, you have the option to. My phone lasts 2 days rather than 1 with it enabled! Speech over. 😄
