### ISSUE TITLE
Rate and Review button is not working properly 

### ISSUE THREAD

**Issue by XAMIR555** [sds100/KeyMapper#190]
#### Project Information

* Repository---------------:[Here](https://github.com/sds100/KeyMapper)
* Project Name------------: [KeyMapper](https://github.com/sds100/KeyMapper/releases)
* Publisher----------------: [sds100](https://github.com/sds100)
* My GitHub account------:[Here](https://github.com/XAMIR555)

#### Expected behavior

When I click on the Rate and Review button, the app should open on the Play Store where I can give feedback about the application.

#### Actual behavior

When I click on the Rate and Review button, no options appear

#### How to reproduce
* Open the [application](https://github.com/sds100/KeyMapper/releases)
* Click the 3 horizontal line at the bottom left
* click on about
* click on Rate and Review  option
* Note the Bug

* Browser/App version-: 1.1.0 Beta 6
* Operating system----: 9.0.0

#### Recording Of The Bug
![20190525_164541](https://user-images.githubusercontent.com/49812927/58368894-07160580-7ea8-11e9-9f4a-4e756018e3b3.gif)

**Comment by sds100** [comment]
Does the device have a internet browser or the play store installed?

**Comment by sds100** [comment]
closing since it works fine on multiple devices.

**Comment by XAMIR555** [comment]
> Does the device have a internet browser or the play store installed?

yes sir installed both

**Comment by sds100** [comment]
Can you try clearing the defaults for the Play Store and your browsers:

![image](https://user-images.githubusercontent.com/16245954/58381108-71ff3380-7fb1-11e9-875e-8f42edc83d9a.png)

![image](https://user-images.githubusercontent.com/16245954/58381117-85120380-7fb1-11e9-92f2-cecbe8c0245c.png)

**Comment by sds100** [comment]
How do i make the images smaller?

**Comment by XAMIR555** [comment]
![Screenshot_20190526-162951_Settings](https://user-images.githubusercontent.com/49812927/58381196-1b710580-7f6f-11e9-879c-f564c46191ef.jpg)
![Screenshot_20190526-162953_Settings](https://user-images.githubusercontent.com/49812927/58381197-1c099c00-7f6f-11e9-9097-d79707d12343.jpg)

**Comment by XAMIR555** [comment]
here is my google play store

**Comment by sds100** [comment]
What happens if you click "Set as default"?

**Comment by XAMIR555** [comment]
sir working fine on 6.0.0 devices

**Comment by sds100** [comment]
I don't know why it isn't working on your 9.0 device. It works on all of my devices with a range Android versions.

**Comment by sds100** [comment]
which browser are you using?

**Comment by XAMIR555** [comment]
sir i am using a google chrome  version 74.0.3729.112

**Comment by sds100** [comment]
Can you clear the defaults for google chrome as well.

**Comment by XAMIR555** [comment]
I have also tried cleanly

**Comment by sds100** [comment]
I'm sorry but I have no idea why it isn't working since I've tried everything I have done before when I have had this problem. Can you try looking online and see what other people have done?

**Comment by sds100** [comment]
This error usually means you have no app installed which can open google play URLs

**Comment by XAMIR555** [comment]
Sir, I do not know  what the problem is

**Comment by XAMIR555** [comment]
Other applications work well

**Comment by sds100** [comment]
For some reason your device thinks it can't open a link to the google play website but it should be able to. Do the other links in the "About" page work?

**Comment by XAMIR555** [comment]
maybe  problem with my devices, its possible

**Comment by sds100** [comment]
yeah. im going to try something in my app then send you an apk to install so i can see if it helps figuring out what is going on...

**Comment by XAMIR555** [comment]
thats good

**Comment by sds100** [comment]
[app-debug.zip](https://github.com/sds100/KeyMapper/files/3220299/app-debug.zip)

github dont allow you to send apks so unzip this and its in there. A separate "debug" version of the app will be installed so it will look like you have 2 Key Mapper apps. You can uninstall this afterwards.

**Comment by XAMIR555** [comment]
i know sir  i try to install in my devices

**Comment by sds100** [comment]
when you click the Rate and Review button. Does a message pop up on the screen?

**Comment by XAMIR555** [comment]
when i click on Rate and Review Button showing a error Not null

**Comment by sds100** [comment]
hmm. and no app opens when you click it?

**Comment by XAMIR555** [comment]
yes no app open

**Comment by sds100** [comment]
that is really strange because that means Android knows a way to open the link and KeyMapper tries to use that app but the app doesn't open.

**Comment by sds100** [comment]
Can you clear defaults for ALL browsing-related apps and any app stores you have?

**Comment by sds100** [comment]
Thank you for pointing out the issue but I'm just going to close it since it seems like it has something to do with your setup. We can still discuss how to fix it.

**Comment by XAMIR555** [comment]
ok sir thanks u

**Comment by sds100** [comment]
No problem! I'm happy to help. 😁
