### ISSUE TITLE
F-Droid build

### ISSUE THREAD

**Issue by hoshsadiq** [sds100/KeyMapper#195]
Hi, can we get a build going on F-Build? I rather avoid Google play.

**Comment by sds100** [comment]
Yeah. Good idea. I'll look into it.

**Comment by Poussinou** [comment]
For this to happen, we'll need a different build flavor that removes proprietary dependencies like firebase for example.
@sds100 We could open [Request For Packaging](https://gitlab.com/fdroid/rfp/issues) if you're willing to write this build flavor.

**Comment by sevospl** [comment]
How is it going with it?

**Comment by sds100** [comment]
I've been unable to devote much time to the app for the past couple of months. I'm going to start working on it bit by bit at the end of this week. I'll try to get an F-droid build done by the end of this week.

**Comment by sds100** [comment]
I'm going to remove Firebase from the Google Play version as well. I want to do my bit to stop tracking of people's devices. I rarely use it anyway.

**Comment by sds100** [comment]
I'm guessing the app doesn't need a privacy policy anymore?

**Comment by hoshsadiq** [comment]
I don't think so. Maybe just a "we don't track you in any way shape or form" or something like that, just for clarity sake

**Comment by sds100** [comment]
Yeah. I'll just add a comment to the top of the existing privacy policy saying as of [next version] there are no tracking libraries and we don't track you in any way. Someone could still install an old version which does track and the old privacy policy would still apply.

**Comment by sds100** [comment]
the merge request: https://gitlab.com/fdroid/fdroiddata/merge_requests/5863
