### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#204]
- notify people who mentioned it.

**Comment by SugoiDev** [comment]
Just noticed this myself. It currently uses more ram than anything else on my device (about 210MB right now). Using LineageOS 15.1 (Oreo 8.1) on a Lenovo K53b36 3GB ram.

**Comment by sds100** [comment]
I think it has been improved slightly in 2.0. When apps are open these days they tend to consume a lot of RAM. I don't think it is entirely the developer's fault, it is just the way they are these days. Key Mapper has to listen to quite a lot of things in the background.
