### ISSUE TITLE
Add info to readme about enhanced data encryption

### ISSUE THREAD

**Issue by SailReal** [sds100/KeyMapper#206]
At first very ingenious app idea and open source apps are always awesome!

While setting up KeyMapper, my phone showed up the following message: "If you turn on Key Mapper, your device won't use your screen lock to enhance data encryption".

Read more about that problem: https://blog.g3rt.nl/android-lollipop-encryption-user-interface-flaw.html

In my opinion, this should me mentioned in the readme and maybe also in the playstore note because it has an impact to the security of the phone.

**Comment by sds100** [comment]
Oh, thanks for pointing that out. I had no clue since I haven't read about it any documentation or forum posts (maybe I didn't look hard enough) and I'd never seen the message myself. Do you have any idea if it still applies to versions newer than lollipop? Thanks.

**Comment by SailReal** [comment]
I've installed Android Pie and see this dialog but haven't looked any further yet, maybe there's another way to get the same functionality without requesting screen notifications....

**Comment by sds100** [comment]
I'm on Android Pie but i dont see the dialog and my phone is encrypted. OnePlus 6T with OxygenOS 🤔

**Comment by sds100** [comment]
I briefly looked through some of the accessibility service documentation just now and couldn't find any mentinon of it. (not saying it doesn't exist, it clearly does).

**Comment by SailReal** [comment]
Hmm strange, my phone is a OnePlus 3T with LineageOS 16.0...weird 😅

**Comment by sds100** [comment]
yup. so you encrypted your phone with lineage?

**Comment by sds100** [comment]
Added a note to the play store description.
