### ISSUE TITLE
keyboard gboard doesn't show

### ISSUE THREAD

**Issue by filipe-silva** [sds100/KeyMapper#211]
Hi there, after selecting keymapper keyboard, it seems the default keyboard stops poping in. 
For instance, I go to WhatsApp and try to type a message but can't because no keyboard appears.

I'm on Android 8.1.
If there's anything more I can help with, just say, thanks!

**Comment by sds100** [comment]
Yeah, that's a limitation of Android. You can only have one keyboard selected at a time so if you want Key Mapper to input text, it has to be the selected keyboard. You only have to select the keyboard for certain actions which it says at the top of the home screen.
