### ISSUE TITLE
Add action option for showing the 'change input method' diallog

### ISSUE THREAD

**Issue by Wilker-a** [sds100/KeyMapper#221]
hello :3

i just wanted to ask for the addition of the option for mapping a key to make it show the "change input method" dialogue (aka "change keyboard" option).

thank you a lot \^_\^

**Comment by sds100** [comment]
Good idea. For Android 8.1+ it will only work if rooted. I hope that's fine for you.

**Comment by Wilker-a** [comment]
thank you \^-\^

does it still work with the hardware keys in Android 5(.1)?

**Comment by sds100** [comment]
Yeah, you should be able to remap the hardware keys

**Comment by sds100** [comment]
implemented

**Comment by Wilker-a** [comment]
thank you :3

**Comment by sds100** [comment]
You can test the action in the latest prerelease on the releases page

**Comment by Wilker-a** [comment]
i have tried to use the Recents button (+hold&vibrate) to open the dialog. the issue now is that the original button's action is still triggered after the Mapper's action is called.

i made this recording:
![smaller settings: hold time: ~300ms; vibration time: ~50ms;](https://user-images.githubusercontent.com/10854855/62014898-5cb3aa80-b196-11e9-83bc-aff12fe28b55.gif)

i haven't tested it with the other buttons yet.

**Comment by sds100** [comment]
Could you try it with the other actions to see if the same happens?

**Comment by Wilker-a** [comment]
i've just tried.

- Back and Home buttons works normally;
- Volume buttons works, but the volume sound is still played upon triggering, although it doesn't actually changes the volume;


some things i have noticed but may be things for other issues:
- Power button can't be set as a trigger, as the screen is turned off whenever pressed. maybe add alternative ways to set up triggers besides recording and waiting a few seconds might fix the problem;
- the trigger doesn't work whenever it is set to two or more buttons and one of these buttons is a volume key or the Recents key.

(sorry for the late reply. i spent a couple of days without internet connection.)

**Comment by sds100** [comment]
No problem, I'm going to be without connection every now and then for a few weeks. 
Android doesn’t allow apps to intercept the power button key event for security reasons.
I'll look into the recents button problem. I had the same problem with the home button a while ago.

**Comment by sds100** [comment]
I've fixed the recents button problem.
