### ISSUE TITLE
stop repeating a key when another key is pressed

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#233]
recreate:
create 2 keymaps with triggers: Vol down + vol up and just vol down. Use KEYCODE_0 and KEYCODE_1 respectively. when you hold down vol down, 1s are typed repeatedly and whenever vol up is pressed a 0 is typed.

expected behaviour: when you hold down vol down, 1s are typed repeatedly and when vol up is pressed the 1s stop being typed and only 0s are typed.

**Comment by kai11** [comment]
This can be useful to convert any bluetooth keyboard to chorded keyboard

**Comment by sds100** [comment]
Hi, sorry but I haven't been able to visit this bug yet. I am very busy studying and when I have spare time I am focussing my attention on redesigning the app for the 2.0 release. Check about the GitHub Actions builds for the latest changes I am working on. I am going to completely rewrite all the logic for detecting triggers anyway in the 2.0 release, so I am not going to work on this bug until then since it is relatively minor.

**Comment by kai11** [comment]
I tested this on 2.0 beta from play store.
Unfortunately, dont work - simultaneous press of 2 keys on hardware keyboard generates both keycodes, not one.

**Comment by sds100** [comment]
@kai11 I've fixed this now. You can test it here https://github.com/sds100/KeyMapper/actions/runs/137088991

**Comment by kai11** [comment]
Tested on CI version with VolUp+VolDn (keycode_0) and VolDn (keycode_1).
Pressing both keys still type 10, not 0.

**Comment by sds100** [comment]
ohh, when they aren't being held down. Sorry, my bad. Should the solution be that the VolDn action is only performed when you release the key?

**Comment by kai11** [comment]
When I held both keys it repeats correct char indeed, but first press generates two characters.
AFAIK hardware chorded keyboards perform character typing on release so chord can be finished - same situation here with parallelTrigger.

**Comment by sds100** [comment]
Yeah, should I add an option for single key, short press triggers to perform the action when it is released rather than when they are pressed down?

**Comment by kai11** [comment]
I understand. Anywhay, from https://twiddler.tekgear.com/
> The Twiddler generates characters by the release rather than the initial press of a key so you do not have to worry about whether you have pressed all the keys in a chord at exactly the same instant.

**Comment by sds100** [comment]
actually, my suggestion wouldn't work. I'm trying to think of the most elegant solution so I don't have to do a lot of "keyevent processing" and unintentionally introduce behaviour most users wouldn't expect.

**Comment by sds100** [comment]
@kai11 I'm going to create a 3rd trigger mode for chorded trigges. Are you wanting to have parallel and sequence triggers with any of the same keys as chorded triggers? It would make life much easier for me if they didn't overlap/interfere

**Comment by kai11** [comment]
ATM Im learning on screen chorded keyboard https://software-lab.de/penti.html and it has both  "arpeggios" (sequences) and chords. Both are very intuitive.
However, only chords as first step are good enough

**Comment by jambl3r** [comment]
added sentiment to #988
