### ISSUE TITLE
Pressing two buttons causes unwanted action

### ISSUE THREAD

**Issue by alekksander** [sds100/KeyMapper#245]
I've installed Key Mapper (1.1.4) just to be able to toggle led (flashlight) on and off with my assistance button. Despite it caused my system to crash and reboot into bootloader(?) once it works fine except for one thing — toggle flashlight is set on long press ( button mapped as 416). I don't want it to trigger it too easil so there is a long press adequate delay. However Key Mapper also toggles flashlight **instantly**  if i press power button and 416 simultaneously. Is this known issue? How could i debug to provide some data? This is clean android 8.1 Thanks.  
 https://framapic.org/oPuCWACnun2f/bGi2VufFceTe.png

**Comment by sds100** [comment]
Hi, I have no idea why the app caused your system to crash. On Android, apps aren't told when the power button is pressed and accessibility services can't either for security reasons. So when you hold down the power button and button 416 Key Mapper just sees the button 416 being pressed which is why it still toggles the flashlight. There isn't anything I can do to fix this. I hope you understand.

**Comment by alekksander** [comment]
okay, just to clarify because i'm not that good at straightforward explanations.
→416 configured to toggle on long press – works if pressed for two seconds
→power + 416 toggles on any duration press – additionaly power button turns screen on as should

i think You understood that correctly, so i'm closing the issue.

ps. i have two leds at back of my cellphone, only one is triggered as flashlight, and other one is only activated by camera application. is there a way to choose which one to operate at the level of api?

**Comment by sds100** [comment]
I'm not sure about that. I don't think there is anyway to control that. Can you try turning on the flashlight with the quick setting and see if it does the same thing?

**Comment by alekksander** [comment]
it does the same thing. other led has to be hardcoded to camera app (unremovable one)

**Comment by sds100** [comment]
okay, there probably isn't anything I can do. That's behaviour I've never seen before.
