### ISSUE TITLE
Android randomly killing ‘Keyboard/Button Mapper’

### ISSUE THREAD

**Issue by Infirme** [sds100/KeyMapper#248]
Hello,

This is not exactly a problem with ‘Keyboard/Button Mapper’, but with the Android 9 system on my phone. Without any intervention on my part, it seems to be randomly killing (and sometimes visibly disabling!) any accessibility app, such as ‘Keyboard/Button Mapper’ or a screen reader app I've installed.

Here's what happens: Between two phone uses, all accessibility apps would stop working. In System Preferences -> Accessibility, I have to toggle these apps Off and On one by one, in order for them to function again. Which they do… until they get randomly shut down again. Do you have solutions for this?

My guess is that Android is over-optimizing either the memory or the battery usage, in effect punishing anyone with disabilities.

Thank you in advance!

**Comment by sds100** [comment]
Hi, that is a really annoying problem. Have you tried disabling battery optimization for the app?

**Comment by sds100** [comment]
No response and the issue isn't specific to the project.

**Comment by Infirme** [comment]
Sorry, I was quite busy and I couldn’t respond before the weekend.

The typical solution, which is to go to _Settings_ on the phone, select _Battery Optimisation_, and set the app to _Not Optimised_, didn’t work for me. Even if ‘Keyboard/Button Mapper’ and my screen reader app were both set to _Not Optimised_, Android was still killing them.

The ONLY SOLUTION that worked in my case is to go to _Settings_, then _Battery_, and to enable _Performance mode_ (also known as _High Performance mode_). It causes the battery to discharge faster and the phone to heat up, but in return, nothing ever gets killed. It’s annoying that it’s not an app-specific solution, but it works for me.

**Comment by sds100** [comment]
No problem. It's good you figured out how to "fix" it. Which device do you have? I haven't seen a "feature" like that before. I wish OEMs would stop having aggressive RAM management.

**Comment by yes215** [comment]
yes ty it worked!

**Comment by NotAkash099** [comment]
Ahhhh I am in Redmi 9 Activ

Well My keymapper which I use
Shows a problem that my phn killed keymapper I have watched many vids my none worked.So,can someone teach me to
solve it?
