### ISSUE TITLE
App constraint

### ISSUE THREAD

**Issue by bahusoid** [sds100/KeyMapper#250]
Would be cool to have option to specify in which programs mapping should be active.
I see it as additional trigger filter in "New Keymap" window that allows to specify list of applications where keymap should be active.

For instance I want Page Up to be remapped as Channel UP but only in one program.

checklist:
- App in foreground.
    - [x] added listing
    - [x] detection logic works
- App NOT in foreground.
    - [x] added listing
    - [ ] detection logic works

**Comment by sds100** [comment]
Yeah. I will add support for it in the next big release. Thank you for giving your thoughts on how to design the interface.

**Comment by sds100** [comment]
Look at the 2.0 plan issue to see what I'm planning on doing. Please leave any comments or suggestions you may have.

**Comment by sds100** [comment]
https://github.com/KieronQuinn/DarQ/ look here for an example of detecting when an app is open.

**Comment by bahusoid** [comment]
Oh... I see some work is in progress in this area... Cool!!!  Just one thought on this topic. Can you also implement some "invert flag".  So by default app constraint means - keymap works only for this app. And when "invert flag" is set - it works for all apps except specified.

It seems this logic can be generalized with other bluetooth issue - by default keymap works only when bluetooth is connected, and when inverted - only when disconnected.

**Comment by sds100** [comment]
Yeah, I'll add a constraint for when an app is NOT in the foreground as well.

**Comment by sds100** [comment]
implemented
