### ISSUE TITLE
Feature request: integration of a T9 input method

### ISSUE THREAD

**Issue by Piciok** [sds100/KeyMapper#263]
Related to [262](https://github.com/sds100/KeyMapper/issues/262):

Since it is currently impossible to emulate keyboard shortcuts without having the Keymapper input method activated, it is impossible to type and emulate the accessibility actions at the same time. From your plan for an upcoming version it s clear that the integration of AOSP keyboard is imminent.

What I found works best with me for better accessibility on keypad-based devices is using a hardware-friendly T9 keyboard which is faster to type on than looking for individual letters using the joystick so it might be of help to others who may benefit from assistive technologies.

Here is a [T9 keyboard app](https://github.com/Clam-/TraditionalT9) that, although abandoned, seems to be working fine with a IR remote of an Android TV box.

Do you think it would be possible to integrate this or create something similar to be used as an alternative input method for devices that have a traditional 12 or at least 10-key number block?

Thanks

**Comment by sds100** [comment]
Yeah, this should be possible.

**Comment by sds100** [comment]
I'm starting to think about how I would integrate proper input methods/keyboards with Key Mapper. I am thinking of making them external apps that can interface with Key Mapper. Do you know of any open source T9 input methods so I could fork it or ask the developer to add the relatively small amount of code to make it interface with Key Mapper?

**Comment by Piciok** [comment]
The project I have linked to in my initial comment seems to be the best candidate. Unfortunately, it does not seem to be maintained anymore, however the original creator has left a compiled apk version which I was able to try and it worked perfectly so this should work for your approach. Keeping my fingers crossed.

**Comment by sds100** [comment]
Since it is _very_ old in the Android world and isn't maintained I am probably better off making my own. A T9 keyboard is simpler than a QWERTY one so it is probably doable. What features are you after?

**Comment by Piciok** [comment]
I believe for a start it would be great if it simply worked, but ideally, the features I would imagine would be needed are:

- multilingual support or at least the ability to map characters E.G> diacritics to certain multiple key presses;
- The ability to remap function keys, especially:
A. the space to be 0 or something else than Hash or Star keys which are not present on remote controls;
B. the functions of arrow keys that could be different when the keyboard is active E>G> to navigate through the text and when it's out of the text fields E.G. to navigate the interface with the screen reader focus method.

Those are the features I see myself using in my unusual use case. Perhaps other users will chime in with some other suggestions.

**Comment by sds100** [comment]
Hi, this is much more work than I originally thought. 😂 I was under the impression you wanted a software T9 keyboard, not one that processed a hardware one. I don't think I can do it, especially considering I don't have a device with a T9 keyboard. Is that project you linked to good enough for your needs? I could fork it and make it a compatible Key Mapper input method just for you. The code for it is really outdated and complicated so I don't feel comfortable releasing it to the stores. I would also have to make you a custom Key Mapper apk that adds support for the forked keyboard since I've made it so that the user has to explicitly tell Key Mapper which keyboard to use.

**Comment by Piciok** [comment]
Yes, that keyboard was good enough for what I need to do. Thanks a lot.

**Comment by sds100** [comment]
Hello,

Here is a Key Mapper and TraditionalT9 apk that work together...


[keymapper-debug-t9-keyboard.zip](https://github.com/sds100/KeyMapper/files/5028610/keymapper-debug-t9-keyboard.zip)
[TraditionalT9-debug-keymapper-compatible.zip](https://github.com/sds100/KeyMapper/files/5028611/TraditionalT9-debug-keymapper-compatible.zip)

**Comment by Piciok** [comment]
Hello and thank you again for your involvement to address my request. I really appreciate that.

I have tried the provided combination today and I did not succeed. I wanted to assign some keyboard shortcuts to my remote's keys and while alt+left arrow finally gave in and worked, alt+right arrow seemed impossible to be configured, perhaps there is an issue with either my keyboard or the way my TV Box interprets key presses as I had some issues getting them to work in other contexts but that's a matter for another issue i guess.

Just to be sure: should I set the Keymapper Debug Basic Input? Will the T9 take over then or shall I set the Traditional T9 anyway?

I will soon lose my everyday access to my test device for this scenario so if I don't comment in a while, and you see it fit, feel free to close the issue so that it doesn't remain on your radar and I'll chime in again once I can test further.

Thanks again.

**Comment by sds100** [comment]
Hello,

Use the Traditional T9 apk, which I sent you, for your keyboard.

1. You need to go into the Key Mapper apk I sent you
2. press the "Select compatible IME". I can't remember what it says so click which ever one is second from the top.
3. Choose the T9 keyboard in that dialog.
4. Your actions should now use the T9 Keyboard apk I sent you.

**Comment by sds100** [comment]
resolved
