### ISSUE TITLE
triggers can be sequences or simultaneous

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#268]

**Comment by sds100** [comment]
implemented

**Comment by sudomain** [comment]
@sds100 I see this is in the 2.0.0 project. Since it's implemented prior to the 1.1.18 release, will it instead be in 1.1.18? Also, are there plans for a 1.1.19 or is it going to 2.0.0. after 1.1.18?

**Comment by sds100** [comment]
It's going to be in 2.0.0.
