### ISSUE TITLE
Feature request: Add support for power dialog menu

### ISSUE THREAD

**Issue by mo123** [sds100/KeyMapper#277]
On tablets and Android media players, there is a power off icon in the navigation bar.
When you press it with touch or a mouse it shows Shutdown, Restart, Sleep.
Android media players also show this menu when you long press the power button on the ir remote.

It would be nice to map this menu to a key.

**Comment by sds100** [comment]
Hi, Android doesn't expose this menu to app developers so it will only be possible to show it with root.

**Comment by mo123** [comment]
There is another app that can map this power menu without root.
Can you maybe check what it does to do it?
Package name: flar2.homebutton - Under Actions - Power dialog

**Comment by sds100** [comment]
oh, my fault. there is an obvious way to do it with the accessibility service. 😂 it will come in the next incremental release in the next few weeks hopefully

**Comment by mo123** [comment]
Thanks, that would be great.
It will be very useful for people that use wifi or bluetooth airmouses with Android media players to shutdown or restart their devices without switching back to ir remotes that require line of sight.

**Comment by sds100** [comment]
Android Lollipop and newer only allows this functionality

**Comment by sds100** [comment]
implemented
