### ISSUE TITLE
Long press double vibration

### ISSUE THREAD

**Issue by dpacmittal** [sds100/KeyMapper#282]
Swiftkey does this really well. Long press a key on swiftkey keyboard and it vibrates twice once one you tap and then once long press is triggered. It's a great haptic feedback to let user know that long press has been triggered.

**Comment by sds100** [comment]
Great idea!

**Comment by sds100** [comment]
- [ ] add option to settings and option to change the delay between the vibrations
- [ ] make it work in the accessibility service

**Comment by sds100** [comment]
implemented
