### ISSUE TITLE
flag to repeat action when keymap is held down

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#287]

**Comment by Wilker-a** [comment]
an option to set the time between actions should be good in this case too (like on a desktop pc when you hold down a key and you can set the speed and delay of the letter inserts) :3

**Comment by sds100** [comment]
I'll add an option for it

**Comment by sds100** [comment]
- [ ] add setting to change the interval

**Comment by sds100** [comment]
implemented
