### ISSUE TITLE
Create new layout for keymap list items

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#299]

**Comment by sds100** [comment]
![image](https://user-images.githubusercontent.com/16245954/75120537-66e24c80-5684-11ea-9e9e-b293bbefb28a.png)

is this a good layout?

**Comment by sds100** [comment]
Should I show the error in the chip for the action, which has a red error symbol, or is it okay to tap on the chip and then show a message explaining the error?

**Comment by germ** [comment]
Perhaps just putting the action/trigger/options into a collapsible element, if there's an error turn the entire header red.

Once collapsed maybe just show the action as the title?

**Comment by sds100** [comment]
Yeah. What about just having a list of text. E.g
imagine this to be a card...

-------------------------------------------
Error ( ! ) Tap for more info

**Actions** Open App, Toggle Flashlight...
**Trigger** Long Press Volume Down...
**Options** Vibrate
**Constraints** Browser in foreground
______________________________________________

**Comment by sds100** [comment]
use arrows and plus sign in the trigger description to signify whether the trigger is in sequence or parallel

**Comment by sds100** [comment]
implemented
