### ISSUE TITLE
Keyboard not enabled after reinstall.

### ISSUE THREAD

**Issue by cinnamonsweets** [sds100/KeyMapper#300]
Device: FireTV Box
App Version: 1.1.7

It seems the app isn't enabling it's keyboard on it's own after a reinstall.
The OS has no Keyboard Settings page to enable keyboards. Only a selection page to select already enabled keyboards.

I have to run

[CODE]adb shell ime enable io.github.sds100.keymapper/.service.MyIMEService[/CODE]

to get it back everytime. Should make the fix button run that if rooted.

**Comment by sds100** [comment]
By enable do you mean _enable_ the keyboard in the Languages and Input settings (or whatever it is called) in the device settings, or do you mean _choose_ it from the list of already enabled input methods?

**Comment by cinnamonsweets** [comment]
There is no option in the OS settings to enable a keyboard; FireTV OS assumes the keyboard it ships with will always be the default and took steps to make it hard for the end user to install their own keyboard.

But for some reason the pop up list that allows you to select an already enabled keyboard does pop up but it doesn't show keymapper as an input method unless enabled via that adb shell command.

**Comment by sds100** [comment]
Oh right, okay. Yeah, you're right, I'll make it run that command if the device is rooted to fix your problem.

**Comment by sds100** [comment]
implemented

**Comment by rbreaves** [comment]
Had to dig into this one just now as my FireTV gave me fits too after having removed it and now just re-adding it..

The name has changed of course so when I tried what was suggested it failed.

ime set io.github.sds100.keymapper/.service.KeyMapperImeService
ime enable io.github.sds100.keymapper/.service.KeyMapperImeService

To get the names of the IME packages just needed to do this, for anyone following after me. Why did the program fail to do this? I don't know.

ime list -a

Additional reading material.
https://forum.xda-developers.com/showthread.php?t=2795603&page=3
