### ISSUE TITLE
Record Trigger stopped working. Was working before.

### ISSUE THREAD

**Issue by cinnamonsweets** [sds100/KeyMapper#301]
Reason for reinstall in the other issue is because "Record Trigger" no longer works. No countdown. The "Choose Action>Key" still detects key presses though. Does it use a different method?

The application's starting screen indicates "Everything looks good!"

Turning on logging and clicking "Record Trigger" doesn't write anything to the log. Again, no countdown.

It has worked before. I don't know what has changed.

**Comment by sds100** [comment]
It seems like the accessibility service has stopped running. Rebooting the device always works for me. Sorry for the long reply, for some reason I haven't received notifications about new issues.

**Comment by cinnamonsweets** [comment]
Hard rebooting didn't work for me. The first time I installed it the app, it had the same behavior but it started working after I tinkered with the app a few times it started working. (The app would ask me for permission to do something and I would freely give it.) I can't seem to find the route I took to get it working the first time so now the app is just collecting dust in my app drawer. So for certain, the app could work but I just don't know what I did to get it working the first time.

**Comment by sds100** [comment]
Which device do you have?

**Comment by cinnamonsweets** [comment]
It's a FireTV box 2nd gen. TWRP bootloader and rooted. Sorry for such a long delay in reply. I don't login often. I was trouble shooting something else today and remembered this.

**Comment by sds100** [comment]
Did you give the app `WRITE_SECURE_SETTINGS` permission?

**Comment by cinnamonsweets** [comment]
I think I did. Do I have to use adb shell for that? If so what were the commands? I don't remember

**Comment by cinnamonsweets** [comment]
adb shell
su
pm grant io.github.sds100.keymapper android.permission.WRITE_SECURE_SETTINGS

rebooted

tested for countdown. still nothing

**Comment by sds100** [comment]
have you uninstalled the app and tried installing it again? Sorry, but I have no idea why this is happening.

**Comment by cinnamonsweets** [comment]
Yes, tried reinstalling too. Don't worry about it though, it's still a neat app when it works. Amazon firetv os is not friendly with mods. If I ever buy another android based media box, it won't be one of amazon's crippled devices.

**Comment by sds100** [comment]
Yeah, definitely. I really like the look of the Nvidia Shield devices.

**Comment by AliOsman67** [comment]
Delete the app and hang up the phone then turn it back on (don't restart) restore the app and it will work I had the same problem so I managed to fix it this way
