### ISSUE TITLE
Remap Key Combos

### ISSUE THREAD

**Issue by Charlotte2A** [sds100/KeyMapper#308]
Hi, I actually sent you an email, but I haven't got any reply yet.
Thanks for the app first.
I'm using Emacs on Termux, but I cannot send key Combos like Ctrl+Space and Ctrl+Alt+v to it properly.
Ctrl+Space turns out to be used to switch keyboard layout by default. I wonder if KeyMapper can help me send these combos.

My phone is rooted, please help me if it is possible to achieve this by KeyMapper or any other means:-)
Thanks a lot!

**Comment by sds100** [comment]
Hi!

Sorry I didnt see your email. Is your aim with the app to input a Ctrl+Space and Ctrl+Alt+V into termux? Will issue #308 solve your problem?

**Comment by Charlotte2A** [comment]
Yeah, actually I want to solve the problem of input shortcuts that includes Ctrl+Space
Such as Ctrl+Alt+Space and Ctrl+Space.

I just found that Ctrl+Alt+v is one of Termux's shortcut and it can be passed to Emacs in a SSH client. So it doesn't matter.

The problem is Ctrl+Space is intercepted by Android to switch keyboard layout and seems to be never passed to applications.

**Comment by sds100** [comment]
Oh yeah, sorry I mean #237. In #237, im planning on adding an action to input a custom keyevent with modifier keys. E.g Ctrl+space. But I'm not sure if Android would also intercept that. I would have to test. Once I get around to working on #237, I will figure this issue out.

**Comment by Charlotte2A** [comment]
Okay, I'll be waiting for the good news.

In setting I found this chart describing the KeyEvent intercepted by Android System instead of passed to applications, where🔍 represents Super key. 
![IMG_20200327_071137](https://user-images.githubusercontent.com/56725529/77705556-ed2edd00-6ffa-11ea-9248-e68fa3956a30.jpg)
Beside these, when I type Ctrl+Space something like this will pop up, so I think it's also interpreted by the system instead user applications:-)
![IMG_20200327_071209](https://user-images.githubusercontent.com/56725529/77705631-2bc49780-6ffb-11ea-9fd4-c047e93cef65.jpg)
![IMG_20200327_071153](https://user-images.githubusercontent.com/56725529/77705634-2f581e80-6ffb-11ea-8b5f-4afc799c7d0d.jpg)

**Comment by sds100** [comment]
fixed
