### ISSUE TITLE
High Battery Consumption with Key Mapper Running

### ISSUE THREAD

**Issue by Gitoffthelawn** [sds100/KeyMapper#311]
I've been performing a bunch of testing of Key Mapper (see #303), and I've noticed that with Key Mapper running, battery consumption is ***much*** higher than with Key Mapper not running.

As a test, I uninstalled Key Mapper and let the Samsung phone sit for 10 hours without touching it.  After 10 hours, the battery dropped 8%.  Not bad.

Then I performed the same test with Key Mapper installed and enabled.  The battery dropped 59%.  Not good. :(

I repeated this test several times, and the results were similar each time.

I hope this can be resolved. :)

**Comment by sds100** [comment]
Oh, wow. The 2.0 update will be a complete rewrite of the app so lets see if it improves it. I am trying to improve the performance of the accessibility service is this update.

**Comment by Gitoffthelawn** [comment]
Great. Thanks.

No rush... just wondering... do you have an ETA for v2.0?

**Comment by sds100** [comment]
The next few weeks/month. I just need to write the keymap detection logic (the hardest bit...). :) You can take a look at the work so far... https://github.com/sds100/KeyMapper/actions/runs/72813117 Are you allowed to download the artifact it made?

**Comment by Gitoffthelawn** [comment]
I am allowed to download the `app-ci.zip` artifact it made.

I humbly don't know what `artifact` means in this context.  Do you?

**Comment by sds100** [comment]
sorry for the long reply. Artifact means something which was made by the build process and in this context it is an apk. It is safe to install. Every commit, an apk is made with the latest changes from that commit.

**Comment by sds100** [comment]
@Gitoffthelawn has this issue been resolved?

**Comment by Gitoffthelawn** [comment]
Sorry, I never had the time to test the artifact you created.  Does v14 include the fixes here?  If not, can you combine it into one version, so I can test it all together.?

**Comment by sds100** [comment]
I'll combine it into one version.

**Comment by Gitoffthelawn** [comment]
Thanks.

**Comment by sds100** [comment]
I've uploaded a new v15 apk in #303

**Comment by sds100** [comment]
No response and no complaints from other people so will close.
