### ISSUE TITLE
Can't "record" Bluetooth double tap action

### ISSUE THREAD

**Issue by higstar** [sds100/KeyMapper#313]
I really want to disable double tap to redial 
Thought this app would be perfect.
Can't seem to get it to intercept the Bluetooth headset button events.
From the description on all store it appears it should be supported. Is this only sorted with root?

**Comment by sds100** [comment]
Hi

I'm unable to remap my Bluetooth headphone's buttons as well. A Bluetooth keyboard is the only Bluetooth device I've been able to remap so far. I can remap the button presses of a wired pair of earphones. I think Bluetooth devices don't tell the phone which button they are pressing (like a keyboard) but tell the phone to redial, or raise the volume with some Bluetooth specific protocol so I don't think it is possible to remap many Bluetooth devices.

**Comment by higstar** [comment]
Ah damn.  Thanks for the explanation :)
I probably need to put a patch in for Android itself to have it as an option to disable.
