### ISSUE TITLE
replace Telegram channel links with a Discord server

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#324]
- [x] replace link within app
- [x] put badge in readme
- [ ] put links in app descriptions
- [x] point users to the help page in the app before they email the developer.

**Comment by sds100** [comment]
here is the invite link: https://discord.gg/Suj6nyw

**Comment by TheTerrarian101** [comment]
> here is the invite link: https://discord.gg/Suj6nyw

We in boiz

**Comment by sds100** [comment]
implemented
