### ISSUE TITLE
Stops working till restart

### ISSUE THREAD

**Issue by itkind** [sds100/KeyMapper#329]
Hi, I am on Android 10, MI 11, when I close all apps (unintentionally) or I leave the phone over night on, Keymapper stops working and I can't make it work till I restart the phone. Is there a way to activate Keymapper without restarting the phone? 

Thank you

**Comment by sds100** [comment]
Sounds like some battery saving "feature". Android puts the device in "doze mode" when it is left for a while and does block some apps, processes from running in the background. It isn't supposed to completely kill apps so it sounds like Xiaomi is being too aggressive at killing apps so turn off any memory or battery optimisation features you can find. There _should_  be a setting, if not then there is not much we can do unfortunately.
