### ISSUE TITLE
long press triggers short press action 

### ISSUE THREAD

**Issue by I338** [sds100/KeyMapper#359]
After the last update, long press and double press actions trigger the short press actions as well. Technically, short press is a subset of long and double press,  but before the update, doing a long press would only do the long press action and nothing else.

**Comment by sds100** [comment]
I think I've fixed it after i released the latest beta. Test here: https://github.com/sds100/KeyMapper/actions/runs/137088991

**Comment by I338** [comment]
Ok, I'll check that. Thanks!

**Comment by sudomain** [comment]
Fixed in beta2 on fdroid

**Comment by sds100** [comment]
Great.
