### ISSUE TITLE
The order at which the trigger buttons are pressed shouldn't matter

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#36]
When checking if a key press combination is a trigger, check if they contain the same, regardless of the order

**Comment by sds100** [comment]
actually, it should.

**Comment by cauerego** [comment]
i still don't see why it should... looks like it took you a week to figure out why. 😄 

but how about a toggle?

**Comment by sds100** [comment]
It just makes life _much_ easier if a trigger must be pressed in the order that the trigger is defined. 😄 Adding a toggle would mean I would have to completely rewrite the detection "algorithm" because it goes off the assumption that the keys in a trigger must be pressed in order. It is theoretically possible but I don't want to pursue it.

**Comment by cauerego** [comment]
that's fair.

but what do you mean with "life much easier"? for coding, i suppose. 😁
