### ISSUE TITLE
constraints for when screen is on and off ROOT only

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#364]
- [x] ROOT only
- [x] show error for screen off constraint if the trigger doesn't work when the screen is off. When "fix" is pressed, show a dialog outlining which triggers work when the screen is off.

**Comment by Wilker-a** [comment]
is hat possible without root by using the permission of "get phone status or identity" or something similar?

**Comment by sds100** [comment]
It is possible but there wouldn't be any point because keymaps can't work when the screen is off.

**Comment by Wilker-a** [comment]
nor by using adb to grant an unusual permission?

**Comment by sds100** [comment]
With ADB you can listen to ALL events happening on every device connected or within a device with very fine detail with the `getevent` command. That is how I'm wanting to make it work for rooted devices. Flar2 who makes Button Mapper supports it for non-rooted devices by running some shell script on the device, which you run through ADB. The major caveat is you have to run this command EVERY time you reboot on your PC. I don't think it is worth it in that case.

**Comment by sds100** [comment]
implemented
