### ISSUE TITLE
Backup/Restore keymaps

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#37]
- [x] multi select keymaps to export.
- [x] add a property for the database version.
- [x] export a keymaplist to .json file.
- ~~[ ] if JSON version < client version, migrate it to correct version.~~ migrating is alot of work. This feature is just for backing keymaps up. They can be migrated by installing different versions of the app to restore them.
- [x] if JSON version > client version, don't allow importing it.
- [x] buttons in the homescreen menu to import and export ALL keymaps above the enable/disable buttons.
- [x] KITKAT+ option to automatically export keymaps to a location whenever they change. when automatically backupping, delete the old file because SAF can't replace files.
- [x] restrict to KitKat+ because developing a different system to get and save files is too much work for a few Jelly Bean users.
- [x] Show Snackbar if the automatic save location doesn't exist anymore. have button to reset the location

See https://developer.android.com/training/data-storage/shared/documents-files
- ~~multi-select keymaps and export them (as another database).~~
- ~~option to import/export a database. copy the rows into the master database.~~

**Comment by sds100** [comment]
store the database version in the file

**Comment by hoshsadiq** [comment]
Would be nice to have it always read from a file if the file exists similar to xmodmap.

**Comment by sds100** [comment]
So have an option to specify a file to read/write your keymaps to?

**Comment by hoshsadiq** [comment]
Not necessarily write. But as long as it can read. Reason I ask is cos i wanna keep it tracked in git so i don't lose the config.

**Comment by hoshsadiq** [comment]
Doesn't even need to configurable. Even if it's on an sd card or in the android home dir for the app.

**Comment by sds100** [comment]
Okay. I'll add an option to "save and read keymaps from internal storage". When the option is turned on, all the keymaps from the appdata folder will be copied over and vice versa.

**Comment by foguetes** [comment]
Please add the ability to save a collection of button remaps as presets and to export them and import them into multiple devices.

**Comment by sds100** [comment]
@hoshsadiq would it be okay to automatically export the keymaps to a location whenever they change? Rather than storing and reading from the live database in another location. I will add an option to import them.

**Comment by sds100** [comment]
implemented
