### ISSUE TITLE
When selecting an existing remap, some elements on the Trigger screen often don't appear

### ISSUE THREAD

**Issue by Wilker-a** [sds100/KeyMapper#374]
2.0.0-beta.2 (Android 5.1.1)

while making more than one remap and then going back to edit mode, the buttons list or the settings box for if triggers are (simultaneous|in sequence) are often not there seemingly at random (either or both) until another (temporary)button is included or another existing remap is selected for then going back.

**Comment by sds100** [comment]
Can you try this apk?

[keymapper-2.1.0-alpha-debug.zip](https://github.com/sds100/KeyMapper/files/4836633/keymapper-2.1.0-alpha-debug.zip)

**Comment by Wilker-a** [comment]
the behavior persists. at first it seemed to happen at every other render of the options screen, but then it seemed to happen at random about 50% of the time

**Comment by sds100** [comment]
okay, ill keep working on it. i found a device which has the same issue.

**Comment by sds100** [comment]
[keymapper-2.1.0-alpha-debug.zip](https://github.com/sds100/KeyMapper/files/4836952/keymapper-2.1.0-alpha-debug.zip)
Can you try this one?

**Comment by Wilker-a** [comment]
seems good so far ^-^

**Comment by sds100** [comment]
Great! I'll merge the fix
