### ISSUE TITLE
Minor detail: allow for sliders to be clicked at any point

### ISSUE THREAD

**Issue by Wilker-a** [sds100/KeyMapper#375]
this should make them a bit more convenient instead of having to always start from the circle \^\^

**Comment by Wilker-a** [comment]
it seems like the red sliders in the Settings screen are fine but the blue dotted ones in the remap setup options have this behavior, so it may be a bug.. also, having two kinds of sliders in the same application sounds a bit redundant to maintain for the purpose of changing color and size

**Comment by sds100** [comment]
I can tap on the ones in remap options as well. I have two sliders because there isn't a nicer Material slider (like in the remap options) for preference screens. Hopefully Material Components one.

**Comment by sds100** [comment]
It could be a big so I'll make sure my Material Components library is up to date.

**Comment by sds100** [comment]
I'm going to close this because it works on all my devices.
