### ISSUE TITLE
Minor detail: allow Trigger recordings to be stopped at any time

### ISSUE THREAD

**Issue by Wilker-a** [sds100/KeyMapper#377]
an accessibility improvement, or something to save a couple seconds depending on how you look at it.

possible confusion would be for the person to notice that the button also stops, or forgetting to press it. a solution i'm thinking of would be to avoid repeating words so it can make a noticeable change in the text length (i can't think of many repetitions of "`RECORD TRIGGER...`" that could keep the size unchanged, so that should be easy, but i am not sure how well would "`STOP RECORDING`" do.), and also, make the button slowly start glowing after 3 to 5 seconds, (not too fast because i think it can kinda make it look like it rushes the user into finishing it).

what do you think? :3

**Comment by sds100** [comment]
I think I will keep the timer but if you want to stop it early you can tap the button while it is counting down.

**Comment by sds100** [comment]
implemented
