### ISSUE TITLE
Dismiss solved alerts

### ISSUE THREAD

**Issue by Wilker-a** [sds100/KeyMapper#381]
maybe not immediately, but a button to dismiss would be enough.

another improvement would be to only show the keyboard alert if any settings related to it are enabled. likewise, the permission alert can include the dismiss button somewhere inside the dialog (or maybe swipe to dismiss would be better) while the instructions for granting permissions should available in the Settings screen (and in About) regardless. \^\^

**Comment by sds100** [comment]
are you referring to the alerts at the top of the home screen?

**Comment by Wilker-a** [comment]
yes

(in a side note, i noticed the help button in the home screen only after writing this issue, so idk if i should heep the suggestion about the help button \^\^')

**Comment by sds100** [comment]
I think I will just add a setting in Settings to hide them. It is simpler than having to implement my own swipe-to-dismiss mechanism and show them in Settings. I find it really useful so I wouldn't want _another_ button up there to dismiss them.

**Comment by sds100** [comment]
implemented
