### ISSUE TITLE
Cut/Copy/Paste Menu

### ISSUE THREAD

**Issue by JonnyTech** [sds100/KeyMapper#391]
Is is possible to create a mapping to the keyboard context (cut / copy / paste / etc) menu?

**Comment by sds100** [comment]
I'll look into it but I doubt it because that would be a security flaw if any app could copy or paste text

**Comment by sds100** [comment]
I can't find any information about how to do this. Do you know any non-root apps that can do this?

**Comment by JonnyTech** [comment]
For the activity send `openContextMenu()` but I do not know if another app can do it, here is the reference: https://developer.android.com/reference/android/app/Activity.html#openContextMenu%28android.view.View%29

**Comment by JonnyTech** [comment]
PS I only want to show the menu, not actually copy or paste any text. It is very awkward trying to hold down text to get the menu to pop up, so wanted to map it to a hardware key

**Comment by sds100** [comment]
I don't think it is possible. I can't get call the show context menu method from outside the app.

**Comment by JonnyTech** [comment]
Ah ok, no problem. As the mapper can send keyboard presses, I assumed that there was a keycode for context menu or right click.

**Comment by sds100** [comment]
I think there could be a keycode but even then, you would have to have the Key Mapper keyboard chosen and that doesn't have a GUI. I'm not sure the key code would work to show the context menu either.

**Comment by sds100** [comment]
I was looking in the wrong place, it is possible to do this with the Accessibility service!

**Comment by sds100** [comment]
implemented @JonnyTech you can test it by downloading the package here https://github.com/sds100/KeyMapper/actions/runs/163350263

**Comment by JonnyTech** [comment]
@sds100 great, thanks! I see options for cut, copy and paste but not for brining up the actual context menu - am I missing something?

**Comment by sds100** [comment]
It isn't possible to show the menu but you can now do Cut, Copy and Pasting. Did you want specialised buttons within the context menu?

**Comment by JonnyTech** [comment]
Ok, got it. Those three buttons are a great help. The menu is handy because it has other options such as `select`, `select all`, `paste as plain text`, `search`, etc which are useful in different situations. The one that I use most is `select` because with my clumsy old fingers it is difficult to start a selection. But I do appreciate your work and am grateful of your efforts and will use the new actions.

**Comment by sds100** [comment]
@JonnyTech https://github.com/sds100/KeyMapper/issues/400 I think I can add an action to start/stop selecting. How would you want it to work?

**Comment by JonnyTech** [comment]
Thinking about it, having lots of different shortcuts is more difficult than one shortcut for a popup menu that has everything on it, which as you confirmed is impossible. I shall think and answer at #400.
