### ISSUE TITLE
Action to select word at cursor

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#400]
- get cursor position with AccessibilityNodeInfo.getTextSelectionStart() and AccessibilityNodeInfo.getTextSelectionEnd(). Handle when it is -1.
- start selecting by specifying start and end position with ACTION_SET_SELECTION

**Comment by JonnyTech** [comment]
Can you detect word boundaries and select them? So if `_` is the cursor position then any place in a word would select it, ie `_h_e_l_l_o_`. The selection stops at whitespace characters or start/end of line too.

**Comment by sds100** [comment]
Yeah, I could do that. I will add an action to "Select word at cursor".

**Comment by JonnyTech** [comment]
Yes please. You're keen!

**Comment by sds100** [comment]
I will try to get it done now. I won't merge it into the 2.0 release but it will go in the 2.1 release to give it time to be tested and find any bugs. Let me know if you end up finding any strange behaviour.

**Comment by JonnyTech** [comment]
Will do, good luck.

**Comment by sds100** [comment]
Implemented.

@JonnyTech here is your apk: https://github.com/sds100/KeyMapper/actions/runs/163862874

**Comment by JonnyTech** [comment]
Thank you @sds100 - it seems to work. If the keyboard is active and I press the mapped key then the current word is indeed selected - with the added bonus of making the context menu appear too. Result! I hope that it was not too much effort. Is is possible to also show the keyboard too in case it is in its hidden state?

**Comment by sds100** [comment]
Yeah, there is a show keyboard action you can also youse in the keymap.
