### ISSUE TITLE
Blocking headphone volume buttons

### ISSUE THREAD

**Issue by dewijones92** [sds100/KeyMapper#401]
Hello
My headphones are a bit fault and are triggering volume up and down erroneously.
How do I block this using the app?

I have created an entry: 
Trigger: Headset Button (this device)
Action: Do Nothing
But it doesn't help

Any tips?
thanks

**Comment by sds100** [comment]
Since that doesn't work I think the headphones themselves are somehow telling the system to increase the volume up and down. This app doesn't work for Bluetooth headphones as well.

**Comment by dewijones92** [comment]
Is there a way to tell the system to ignore the headphones themselves telling the system to increase the volume up and down?
It was my understanding that this app is able to do this?
Many thanks

**Comment by sds100** [comment]
My app can only do it if the system passes the Key events to the app. If it doesn't, the app can't do anything.  I don't know of any setting to block headphone buttons. Maybe there is a way if you're rooted.

**Comment by sds100** [comment]
Key Mapper can't fix this problem.
