### ISSUE TITLE
show warning that a user can't unlock their phone if they choose the Password screen lock.

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#402]
show it when:
- [x] Enabling Key Mapper keyboard.
~~- [ ] Choosing Key Mapper keyboard.~~ Can't show dialogs outside of the app.
- [x] creating a Key Event action.

Title: Key Mapper keyboard has no GUI!
Message: The Key Mapper doesn't have a GUI but it will come in a later release. If you have a **Password** screen lock you will NOT be able to unlock your phone if this keyboard is chosen. If you have any other screen lock chosen, such as PIN, Pattern then you are fine. They can turn on the notification to switch the keyboard but they MUST have granted WRITE_SECURE_SETTINGS permission to the app and make sure notifications aren't turned off on the lockscreen.

Positive button = Okay

**Comment by Wilker-a** [comment]
it should be enough to implement a failsafe, just in case. if there is any chance that someone might forget and leave it on, someone *will* forget.

**Comment by sds100** [comment]
Yeah, that is probably a good idea... but there isn't anyway the app can change the keyboard. It has only been 2 people so far so I think the chances are very unlikely until I add a GUI to the keyboard. I hope to do this very soon. I just got some extra storage which means I can properly compile the AOSP keyboard by building AOSP.

**Comment by Wilker-a** [comment]
there is a keyboard GUI on KeePass DX that is visually small enough to make it so it doesn't keep anything on the screen besides the Change Keyboard button. do you think it might be worth to have that?

but there is also the thing about notifications. i don't know if the keyboard notification will appear on the lock screen if notifications in general are set as hidden, so it might spare some work and apk size if it does.

**Comment by sds100** [comment]
that is a good idea. I'll see if Key Mapper is allowed to launch the keyboard picker dialog from outside the app from the keyboard. After Android 8.1 apps can't show the keyboard picker dialog outside the app.

**Comment by sds100** [comment]
implemented
