### ISSUE TITLE
Backup and restore

### ISSUE THREAD

**Issue by JonnyTech** [sds100/KeyMapper#406]
When upgrading from beta to release I am trying to export my mappings and import them. I found the option to backup from beta but in the release I can find no restore option. Can you advise please?

**Comment by sds100** [comment]
Which beta/alpha version were you on? None of the beta versions should have had backup and restore in them. I haven't added backup and restore to the stable releases yet which is why you don't see it.

**Comment by JonnyTech** [comment]
I was using the CI build that you directed me to from another issue (#400). No problem, I shall re-enter manually.
