### ISSUE TITLE
3 keys sequence not cancelling 2 keys sequence

### ISSUE THREAD

**Issue by heavenblest** [sds100/KeyMapper#407]
Hi, I'd like to thank you for this app! It's almost making me able to fully remap my portuguese keyboard. The only trouble I'm having is that if I set 2,3 as triggers for typing '4', and 1,2,3, for '5', the longer sequence does not cancel the shorter and the result is "45". In portuguese we need to hit "´ + a" to get 'á' and "((hold)shift + ´) + a" to get 'à'.

This behavior would be appreciated on the next update.

**Comment by heavenblest** [comment]
> Hi @heavenblest ,
> 
> I think I've fixed the issue. Can you test the fix here and comment if it works? https://github.com/sds100/KeyMapper/suites/974991842/artifacts/12409484

It's working!!

There's only one more problem that I forgot to mention... it needs to cancel 1 key trigger too. If i set an 1 key trigger, like, c = (text) "test3", it will cancel the 2 keys trigger composed by the key c (ex. a,**b,c**) but not c itself.

a,b,c = (text) "test1"
b,c = (text) "test2"
c = (text) "test3"

Hitting a,b,c results in "test3test1".

Another nice improvement would be to implement ctrl, alt and shift as modifiers in the sequence too.

Keep up the good work!

**Comment by sds100** [comment]
okay, I'll try to fix that as well

**Comment by sds100** [comment]
https://github.com/sds100/KeyMapper/suites/995324354/artifacts/12834599 this should have fixed it

**Comment by sds100** [comment]
I consider this fixed
