### ISSUE TITLE
Tap coordinates action interrupts finger press on screen

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#417]

**Comment by sds100** [comment]
Can't fix. https://developer.android.com/reference/android/accessibilityservice/AccessibilityService#dispatchGesture(android.accessibilityservice.GestureDescription,%20android.accessibilityservice.AccessibilityService.GestureResultCallback,%20android.os.Handler)

"Dispatch a gesture to the touch screen. Any gestures currently in progress, whether from the user, this service, or another service, will be cancelled."

**Comment by kshatriya-abhay** [comment]
In case anyone else is wondering, `adb shell input tap X Y` also interrupts the gestures in progress.
