### ISSUE TITLE
tutorial videos

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#425]
- [x] create a Key Mapper channel
- [x] create "channel art". recommended is 2560x1440 and max 6MB
- [x] video watermark. used round app icon
- [ ] put a link to the tutorial video for the GUI keyboard in the Key Mapper GUI Keyboard store description.
- [ ] put the video as an asset on the GUI keyboard google play listing.

Advertise it in the app.
- [x] put a link in the About page
- [ ] put a link at the top of the Help page.

Video specification:
1. device must be in "demo mode". Enable in Developer Options -> "System UI demo mode"
2. show tap circle. Enable in Developer Options -> "Show taps"
3. No watermarks or artifacts from screen recordings.
4. portrait
5. atleast 720p

Screen recording:
- use ADB if the device doesn't have a built-in high quality and unobtrusive mechanism.

1. `adb shell screenrecord --bit-rate 40M /sdcard/record.mp4`
2. upload the `record.mp4` file here. it will be in the "internal storage" folder. 

Video ideas
- [x] ~~how to use for Minecraft (not cheating). Show the user the menu to change how an action is performed. E.g changing the repeat rate.~~ The community can make videos for Minecraft
- [ ] how to create a keymap and customise actions. talk about all the features, e.g constraints.
- [ ] how to use the GUI keyboard. only do this once the 2.1 release is finalised
- [ ] granting WRITE_SECURE_SETTINGS permission. Use Windows Sandbox to make sure the system is configured in the stock configuration as most users will expecting it to be. 
- [x] capture bug report

**Comment by hoshsadiq** [comment]
Hello! Not a video idea, but I noticed you had layed out information on how to grant the app the right permissions when the accessibilities page doesn't exist. Seems this wasn't the case for the keyboard being enabled. Turns out the Fire TV is affected by both of these things. I've been able to update the keyboard through ADB using the following commands:

```
adb shell ime enable io.github.sds100.keymapper/.service.KeyMapperImeService
adb shell ime set io.github.sds100.keymapper/.service.KeyMapperImeService
```

Might be worth adding this in a similar manner as the accessibility service.

Wasn't really sure where to put this so sorry if it's in the wrong place. I'm happy to open a new issue if you like.

**Comment by sds100** [comment]
Hello, yeah granting WRITE_SECURE_SETTINGS permission doesn't fix that problem. The app already executes that command if Key Mapper has root permission. Take a look at this issue #469 because it could make it possible for Key Mapper to execute that command without root. I am going to make it work when I make Key Mapper officially support Android TV.

**Comment by sds100** [comment]
Not doing the rest of this. The documentation website has somewhat replaced this
