### ISSUE TITLE
Automatically change input method???

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#43]
https://github.com/aosp-mirror/platform_frameworks_base/blob/pie-release/services/core/java/com/android/server/InputMethodManagerService.java

Intent intent = new Intent(Intent.ACTION_INPUT_METHOD_CHANGED);
                intent.addFlags(Intent.FLAG_RECEIVER_REPLACE_PENDING);
                intent.putExtra("input_method_id", id);
mContext.sendBroadcastAsUser(intent, UserHandle.CURRENT);

val imeManager = ctx.getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager
imeManager.enabledInputMethodList[0].id 

When the user disconnects a keyboard, automatically go back to the input method chosen before the device connected.

**Comment by gamesfrager** [comment]
Hello. Is it possible to trigger the pause with Tasker? Would you please let me know how exactly should an intent in Tasker be setup to trigger the pause/resume?

Much appreciated.

**Comment by sds100** [comment]
No it isn't but I will add an Intent API to do this. :)

**Comment by gamesfrager** [comment]
:) Thanks for the reply. I asked about this in light of my other enhancement ticket for switching the input method on input field focus. But this might be helpful for non-rooted devices as well.

**Comment by sds100** [comment]
Android 11 added the ability for accessibility services to change the input method so no special permissions that are complicated to grant are required any more!

**Comment by sds100** [comment]
@gamesfrager You can test the new Intent API for pausing key maps. Here is a guide for getting the testing builds https://docs.keymapper.club/contributing.html#becoming-a-tester and a guide for the new API https://docs.keymapper.club/user-guide/controlling-mappings.html#intent-api

**Comment by gamesfrager** [comment]
You bet. I'll test it tonight and report back.
Thank you for all your work.

**Comment by gamesfrager** [comment]
Success! I downloaded the version from https://github.com/sds100/KeyMapper/actions/runs/947220527 and created the intent in Tasker. O used the `toggle`, `pause` and `resume` intents, they all worked. Nice work.

**Comment by sds100** [comment]
Cool
