### ISSUE TITLE
Features request/enhancement

### ISSUE THREAD

**Issue by abhishekabhi789** [sds100/KeyMapper#445]
### Feature requests.

**General**
• Kill foreground app action
• Launch last app action
• Send Intent action
• Restore default virtual keyboard when user taps input fields once/twice with.
**Android TV**
•  Map volume keys of android TV (it has no dnd mode).
• Brightness +/- action not working on TV
• Mute action (Mi TV 4A has no dnd options, so dont know about other TV's)
**Other**
• Tasker Event / state plugin
Event for simply map buttons per app basis, and state for doing something while vol key is held pressed (like voice recording)

……………………………………………………………………………………………………………

###Enhancement

• Consider releasing this app for android tv too, since android tv remote has few buttons and this app is very helpful.
• I made a slide gesture by home button -> back button (in sequence) and linked a Tasker action (run _input swipe_ command on shell) via App Shortcut - Task Shortcut, however while sliding like that, home button single press event occurs first then the slide gesture.  Then I remapped home button to 'do nothing' and I found its working as expected(ie tasker slides on the screen without going back to home screen). I changed duration and delay to some random values, but no significant effect on this issus. I need to  remove single press event (system default/keymapper custom) to execute an in sequence or simultaneous trigger to occur. 
Device : Redmi Note 4
ROM : Resurrection Remix OS 8.5.9 (Android 10)
Keymapper version : (2.0.1)

**Comment by sds100** [comment]
### General
• Kill foreground app action. This is only possible if the device is rooted. Is that fine?
• Launch last app action. Does the double press recents trick work?
• Send Intent action. #112 It hasn't had a lot of requests so it isn't high priority right now.
• Restore default virtual keyboard when user taps input fields once/twice with. In the 2.1 update I am adding support for a GUI keyboard so this should alleviate the pain of not having a proper keyboard. 😄 Can you test the keyboard on your TV to make sure it works properly. test releases can be found here: https://bit.ly/keymapper-keyboard

### Android TV
• Map volume keys of android TV (it has no dnd mode).
• Brightness +/- action not working on TV. Does Android TV provide a way to do this? The brightness actions use the Android APIs to do this. From my experience the brightness of a monitor/TV is controlled by the monitor/TV itself and can usually only be changed with a 3rd party DDC utility on the OS.
• Mute action (Mi TV 4A has no dnd options, so dont know about other TV's). I'll try to fix this.
Other
• Tasker Event / state plugin
Event for simply map buttons per app basis, and state for doing something while vol key is held pressed (like voice recording). So you want a "Key Mapper" Tasker Plugin so can add an event in Tasker when a button is pressed and a state when a button is being held down? Constraints can restrict keymaps to specific apps if that is what you want.

**Comment by abhishekabhi789** [comment]
1) No problem I've root. I understand now a days people have less interest in root, but consider implementing this action. Right now with tasker there's some delay occurs, and it also tries to kill launcher (i whitelisted certain apps including system ui to prevent it).
2) Double tap works fine. I use Tasker to launch last opened app.
3) Thanks in advance.
4) I'll test it later.
**Android TV**
5 & 6) I don't know about that, but I found some people using adb wifi on Tasker app to  do some root actions without actually rooting there device.  So i guss keymapper can also use the same trick to adjust vol/bright .
7) I used keycode mute action , and it's not working with DTH live TV (RCA  connection)  or VLC Player. (If you are working on it, please add half mute and full mute steps too) (1 click mute & 2 click mute separately available actions) (2click mute first reduce to 50% and then 100% then unmute, like in old TV's)
8) Yes, a Tasker plugin feature is really helpful. Right now every tasks are executed after some delay.

(Sorry to reopen it, i found it's closed while typing this😁)
Thanks.

**Comment by sds100** [comment]
I've made issues for all the requests.

**Comment by abhishekabhi789** [comment]
I tested the keyboard app from the link you mentioned above. In my phone worked just like a keyboard. Nothing found relating to keymapper. Disabled keymapper keyboard and found keymapper unable to perform keyevent actions.

In android tv, not showing on drawer, after launching configuration can be done with tv remote. However while typing dpad keys not doing anything on screen. I pressed ok after random dpad movements but no keys are pressed, no letters are typed, nothing moves on keyboard or screen.

**Comment by abhishekabhi789** [comment]
Ive a message automation task on Tasker that send a message using enter key event on tasker and restore my default keyboard after the execution of task. 
So you can also try the same* instead of creating an actual keyboard.
* Before execution of keyevent, change default keyboard and after that restore it (may be with root, no problem if).
