### ISSUE TITLE
Not all aps are visible/selectable from settings

### ISSUE THREAD

**Issue by mdhry45sw** [sds100/KeyMapper#446]
Hello,

SDMC DV8545 Android TV BOX
Not all aps are visible from settings menu.
As you can see below there is lack of: TVP VOD (com.tvp.vodtv.tv), Player (pl.tvn.player.tv) (polish vod's) or HBO GO (eu.hbogo.androidtv.production)

![1](https://user-images.githubusercontent.com/64702528/91941530-a8ba1280-ecf9-11ea-98a5-227526e0b4ae.png)
![2](https://user-images.githubusercontent.com/64702528/91941533-a952a900-ecf9-11ea-8ed0-9a36f8c087a1.png)
![3](https://user-images.githubusercontent.com/64702528/91941535-a9eb3f80-ecf9-11ea-98bf-707825c4d682.png)

**Comment by sds100** [comment]
Hello,

I have added a button in the upcoming 2.1 release. You can get the latest alpha build from the GitHub Actions tab for this repo. It has a different package name therefore, it won't affect you stable installation.

**Comment by mdhry45sw** [comment]
Found it. thanks
