### ISSUE TITLE
Cannot unpin screen while key mapper mapping any navigation keys.

### ISSUE THREAD

**Issue by abhishekabhi789** [sds100/KeyMapper#452]
Pinned an app using android's screen pinning feature.
While back button is mapped with long press trigger, i was unable to perform long press to exit from screen pinning.
I disabled only back button long press action and still system not detecting back button long press and not unpinning the screen.
Then used pause feature in the app and found i can exit from screen pinning.
I tested on firefox and Tasker, and killed keymapper with tasker when I get stucked.
Android : 10
Version : 2.0.1

**Comment by sds100** [comment]
Hi,

Did this happen in the old 1.1.7 version? Could you upload a screenshot of your Key Mapper homescreen so I can see your configuration?

**Comment by abhishekabhi789** [comment]
![Screenshot_20200903-063416265](https://user-images.githubusercontent.com/52370265/92059865-f7c27f00-edaf-11ea-9ee0-e5ce3820b97f.jpg)

**Comment by sds100** [comment]
Isn't it expected that if you map a long press of the back button that holding it down won't unpin the screen. Would this feature request solve your problem? https://github.com/sds100/KeyMapper/issues/437

**Comment by abhishekabhi789** [comment]
Yes.

**Comment by sds100** [comment]
great. 🙂 I've added it in the upcoming 2.1 release.
