### ISSUE TITLE
Add Shizuku support to monitor key events instead of accessibility service

### ISSUE THREAD

**Issue by thetoolz** [sds100/KeyMapper#469]
Shizuku
Let your app use system APIs directly
https://shizuku.rikka.app/
https://github.com/RikkaApps/Shizuku

Use system APIs elegantly
Forget about root shell, you can use APIs with higher privileges "directly". Also, Shizuku is significantly faster than shell.

Support adb usage
If your "root required app" only needs adb permission, you can easily expand the audience by using Shizuku.

use Shizuku to avoid using Accessibility Service.

Apps using Shizuku
https://shizuku.rikka.app/apps.html

Developer guide
https://github.com/RikkaApps/Shizuku/blob/master/README.md

useful for Fire tv since update 6.2.7.3
Accessibility Services Stopped working

Start Shizuku on Fire TV / Android TV
adb debugging enable in settings on tv
(Only available on tv)

usb debugging pop up will show up to allow
Running of adb command

will only work on fire tv /android tv

adb shell sh /data/user_de/0/moe.shizuku.privileged.api/start.sh

Option to run adb shell command
tasker & tasker adb shell plugin

**Comment by thetoolz** [comment]
useful for Fire tv since update 6.2.7.3
Accessibility Services Stopped working

**Comment by sds100** [comment]
So Fire TV doesn't support accessibility services at all?

**Comment by thetoolz** [comment]
@sds100 yes no accessibility

**Comment by sds100** [comment]
oh, okay.

**Comment by sds100** [comment]
Do you know if shizuku can detect keyevents?

**Comment by thetoolz** [comment]
@sds100 to know for sure
would have to submit issue to
https://github.com/RikkaApps/Shizuku

**Comment by thetoolz** [comment]
@thetoolz I'm guessing yes as long as android api on Device supports key events

**Comment by sds100** [comment]
If the user reboots a non-rooted device do they have to setup Shizuku again through adb?

**Comment by thetoolz** [comment]
Yes on fire tv i use tasker
& tasker adb shell plugin

To boot Shizuku on reboot
I run a tasker task which
runs adb command automatically

**Comment by sds100** [comment]
oh, okay. I don't understand, if Tasker can perform the command to start Shizuku why can't Shizuku?

**Comment by thetoolz** [comment]
@sds100 The developer has not added fire tv support most android devices don't have adb debugging only android TV's

Is not optimized for tv
& not originally made for tv

**Comment by sds100** [comment]
what do you mean by adb debugging? You can use ADB on all devices so I'm guessing you're referring to something else. I'm trying to figure out how this all works permission-wise because you said that you can start Shizuku with Tasker after rebooting. I'm going to have a play with Shizuku now.

**Comment by thetoolz** [comment]
@sds100 you don't necessarily need to use tasker could use
AutomateIt & AutomateIt Shell Plugin

& I was saying on android tv you don't need a second Device to run adb command

**Comment by sds100** [comment]
Ohh, okay

**Comment by sds100** [comment]
So you can use ADB wireless out of the box on Android TV as described in this article? https://www.androidpolice.com/2020/09/05/how-to-sideload-any-application-on-android-tv/ If that is so then I'm guessing those apps just connect to the TV over the network? If so, that is pretty cool and opens a world of opportunities. This all makes sense now. Thank you for clarifying. 😄

**Comment by thetoolz** [comment]
@sds100 android 11 will have wireless debugging built in

**Comment by sds100** [comment]
Ooops, i edited you comment, sorry.  Yeah, so Android TV older than Android 11 doesn't support ADB wireless? I was under the impression that it did from what you were saying.

**Comment by sds100** [comment]
What im asking is, on older Android TV versions how did you use ADB?  Android TV's dont have a USB port that you can plug into a PC and then use ADB.

**Comment by thetoolz** [comment]
@thetoolz no not wireless debugging through usb debugging you have to allow app to use it

 usb debugging pop up will show up to allow it

 but will only work on fire tv /android tv

For example
Was able to create a
Mouse Toggle for Fire TV Clone 1.12
https://drive.google.com/file/d/12-UCwEvWuukwFL5u7O724kJ5iHGAX9Fi/view?usp=drivesdk
Steps are below
1.Install this version of Mouse Toggle on fire tv

2.Open the app
Wait a few seconds on white screen

3.Using built in joystick pointer in app

4.Click send
There will be a usb debugging pop up
Click allow usb debugging
& Click ok

Mouse Toggle is now enabled

**Comment by thetoolz** [comment]
@sds100 read this article about adb debugging

How to enable ADB debugging on an Amazon Fire TV or Fire TV Stick https://www.aftvnews.com/how-to-enable-adb-debugging-on-an-amazon-fire-tv-or-fire-tv-stick/#:~:text=From%20the%20Fire%20TV%20or%20Fire%20TV%20Stick%E2%80%99s,%E2%80%9CADB%20debugging%E2%80%9D%20to%20turn%20the%20option%20to%20%E2%80%9CON%E2%80%9D.

**Comment by sds100** [comment]
Oh, thank you so much! Everything makes much more sense now. Sorry, I didn't realise it was a completely separate Fire TV specific feature.

**Comment by zacharee** [comment]
I made a fork of the `develop` branch with basic Shizuku support. It still needs the Accessibility service, but keys that would normally require the IME service now go through Shizuku. Right now, you have to grant the Shizuku permission from the intro slider.

https://github.com/zacharee/KeyMapper/tree/develop

[keymapper-2.3.0-alpha-debug.apk.zip](https://github.com/sds100/KeyMapper/files/5927149/keymapper-2.3.0-alpha-debug.apk.zip) (Remove the extra .zip extension).

**Comment by sds100** [comment]
@zacharee wow, thank you! the code looks fine but there are some things that I'd like you to change. could you create a pull request please?

**Comment by zacharee** [comment]
https://github.com/sds100/KeyMapper/pull/585

**Comment by sds100** [comment]
chickenhook restrictionbypass seems to require api 19 at least. is there a way to not use it?

**Comment by sds100** [comment]
@thetoolz i dont how to use shizuku to detect key events. I don't think it is possible because the Shell app on the device doesn't have permission to monitor input events.

**Comment by zacharee** [comment]
You can monitor KeyEvents at least without an AccessibilityService by hijacking the UiAutomation stuff. It needs Shizuku, but you can use (UiAutomationConnection)[https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/app/UiAutomationConnection.java] and your own client implementation. (UiAutomation)[https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/app/UiAutomation.java] has an example implementation of the needed IAccessibilityServiceClient.

**Comment by sds100** [comment]
can you capture input events even if the input events are being sent to other apps?

**Comment by zacharee** [comment]
It's basically creating a pseudo Accessibility Service, so it receives whatever those receive.

**Comment by sds100** [comment]
do you know how to code it?

**Comment by sds100** [comment]
This solution wouldn't work for the original poster because UI automation seems to use the accessibility service API. the Fire TV doesn't have the accessibility APIs apparently.

**Comment by sds100** [comment]
There isn't a way to monitor input events without using an accessibility service because the `android.Manifest.permission.MONITOR_INPUT` permission can't be granted to apps. I'm working on Shizuku support in Key Mapper for other things like automatically granting WRITE_SECURE_SETTINGS permission and inputting key events. I will create a separate issue for this.
