### ISSUE TITLE
wrong keyboard names

### ISSUE THREAD

**Issue by cauerego** [sds100/KeyMapper#470]
i'm testing 2 keyboards right now, and they both show up as "Bluetooth 3.0 Keyboard", per 1st screenshot:
![Screenshot_20200923-114447](https://user-images.githubusercontent.com/560418/94003694-7f8a2080-fd93-11ea-8e55-61677432ad0e.png)

but i have named them differently on the system bluetooth settings, per 2nd screenshot:
![Screenshot_20200923-114525](https://user-images.githubusercontent.com/560418/94003710-86189800-fd93-11ea-8433-6fc885a1f092.png)

ps: thanks for this amazing free app!!!

**Comment by sds100** [comment]
Hello,

The names in the system settings aren't visible to other apps. Key Mapper uses the standard API to get Bluetooth device names.

**Comment by cauerego** [comment]
you still could offer to rename them manually, or at least add a random identifier to differentiate them! 😒

**Comment by sds100** [comment]
Every input device in Android has a unique "descriptor" and this is what Key Mapper uses and saves to identify devices. Would it be okay to have an option in the settings to show the first 5 characters (the whole thing is very long) of the descriptor next to the device name?

**Comment by cauerego** [comment]
of course!

then wait for the screenshot that will hopefully never come with 2 devices which contain the same first 5 characters... 🤣

**Comment by sds100** [comment]
implemented
