### ISSUE TITLE
gifs!

### ISSUE THREAD

**Issue by cauerego** [sds100/KeyMapper#471]
how about adding gif support? you know, like in gboard...

or rather, anyone already can suggest a good app to combo with gif support, if there's any?

**Comment by sds100** [comment]
Is this for the new Key Mapper GUI keyboard? If so I'm not going to be a keyboard developer and add these features.

**Comment by cauerego** [comment]
well, when the key mapper requires to be the keyboard for some of its key functions to work, that's a keyboard already developed right there... but there's no need to develop the rest of the keyboard, since the intent is for a physical one.

anyway, looks like there's not enough "entropy" here for any of my suggestions, for now. just let them die, opened or closed, whatever.

and enjoy the ride! 😘

**Comment by sds100** [comment]
I'm going to close this since I won't add gif support. It is a nice feature that I do use in other apps but it is a lot of work for an app that isn't designed to be a completely featured keyboard. You probably understand. 😄
