### ISSUE TITLE
clipboard

### ISSUE THREAD

**Issue by cauerego** [sds100/KeyMapper#472]
something like integrating it with clipto would be ideal!

right now i'm using ctrl+shift+v but that's still quite troublesome.

**Comment by sds100** [comment]
What do you mean integrate with clipto?

**Comment by cauerego** [comment]
clipto is my current clipboard app. much better than anything else i've tried so far, although it have been nerfed by Android 10 and can't monitor the clipboard anymore, unless it was a keyboard itself, like gboard.

**Comment by sds100** [comment]
Do you know how to integrate with clipto? Do they have an API?

**Comment by cauerego** [comment]
don't know. i don't have much resources for coding, and haven't really done anything significant in a long time.

i just want to have a better clipboard history. it's great for backup and for copy & pasting.

**Comment by sds100** [comment]
closing unless a way for Key Mapper to communicate with clipto is found

**Comment by cauerego** [comment]
communicating with them should be easy... let's see https://github.com/clipto-pro/Android/issues/32

if you want, i can open an issue about it there. but it'd probably be best if you do it.

that being said, there is at least another good clipboard app out there which is fully open source and good enough. i don't remember it's name, but i changed it for clipto for convenience. clipto was, and probably still is, more complete and functional.

you don't need to limit this issue to clipto, at all.

**Comment by sds100** [comment]
I don't think I need to add a special action for a specific clipboard app because I've now created an Intent action. This is how any clipto action would have worked under the hood anyway. You'll have to find a clipboard app that has an intent API so that other apps can tell it what to do. Or you'll have to add a feature request for one.
