### ISSUE TITLE
I've tested the 2.1.0 Alpha!

### ISSUE THREAD

**Issue by heavenblest** [sds100/KeyMapper#477]
Sorry for the delay... I haven't checked my e-mail for a while.
[https://github.com/sds100/KeyMapper/issues/407](url)

3 keys sequence canceling 2 keys sequence and 1 key trigger. (working perfectly)
2 keys sequence canceling 1 key trigger. (sometimes it does not cancel, especially if the first key in the sequence is shift)

Almost there!

**Comment by heavenblest** [comment]
> This 2 key sequence keymap cancels the 1 key trigger for me. Can you give me an example of one that doesn't cancel?

Wait! Only now I've noticed that you released the 2.1.0 Beta... that one is canceling flawlessly!

Let me buy you a coffee!

I will also record a video to tell people of portuguese language using Android TV (which does not include portuguese in G-Board) to try and support your app.

**Comment by sds100** [comment]
Great! Happy to hear that everything is working. 😄 Thank you for the coffee ☕ and for the video!
