### ISSUE TITLE
input keyevents through the shell are slow

### ISSUE THREAD

**Issue by ildar** [sds100/KeyMapper#482]
Following up https://github.com/sds100/KeyMapper/issues/157#issuecomment-647117738 :
> input keyevents through the shell is much slower.

I'm using "Open Menu" action and it takes 1+ sec. to accomplish.

Are there ways to speed it up? E.g. making the app system?

**Comment by sds100** [comment]
Yeah, there should be. It's because I've been lazy and am making a new process every time. I'll have one process constantly running.

**Comment by sds100** [comment]
should be fixed. one su process is created throughout the accessibility service lifecycle. You can test the artifact here https://github.com/sds100/KeyMapper/actions/runs/315701369.

**Comment by ildar** [comment]
Awesome, thanks a lot!
I'll test and give feedback

**Comment by ildar** [comment]
Just tested.
Well, it is definitely faster, probably twice as fast. Though most users
will treat it slow anyway. But for me it's good. 👍

**Comment by ildar** [comment]
I'm sorry, I'm not so sure now.
My phone is quite slow. I suggest that someone test this change.
Today tests shew the same 1.5-2 seconds on all three: 2.1.0-beta1, CI and
beta3.
