### ISSUE TITLE
The app list is not showing android tv apps with only leanback in manifest

### ISSUE THREAD

**Issue by mauclair9** [sds100/KeyMapper#487]
Thanks a lot for this great and open source application.

It works great in nvidia shield with android tv 9.

On ADD ACTION and then on APP, almost all installed applications are shown, can be selected and then launched with the selected shortcut.

The only problem is that some applications have only leanback_launcher on their manifest so they are not shown and so can not be selected, for example you can install: https://play.google.com/store/apps/details?id=gr.cosmote.cosmotetv.androidtv and then try ADD ACTION with it.

If you have the time sometime to look into it, please check this thread for a similar problem and solution: https://github.com/alescdb/LauncherTV/issues/12

Perhaps there should be some change here, unfortunately I don't know enough to help you: https://github.com/sds100/KeyMapper/blob/b559dd8fb306e56ca2103aedb3dfaf861a85d5b4/app/src/main/java/io/github/sds100/keymapper/data/model/Action.kt#L107

Many thanks for your efforts.

**Comment by mauclair91** [comment]
Thank you for taking note of it.

When you look into android tv support, another bug is that on ADD ACTION, the APP SHORTCUT list is empty.

Again, your work is very much appreciated.

**Comment by sds100** [comment]
Yeah, there probably aren't any app shortcuts on Android TV? I'll leave it in there because maybe someone has got them.

**Comment by mauclair91** [comment]
Hello, I have tried https://play.google.com/store/apps/details?id=flar2.homebutton and the app shortcuts are working, I hope they don't require too much work to implement them.

Thanks for your attention.

**Comment by sds100** [comment]
fixed
