### ISSUE TITLE
In-app Fdroid link is broken for the separate KeyMapper keyboard app

### ISSUE THREAD

**Issue by sudomain** [sds100/KeyMapper#489]
While trying to "Get the new Key Mapper Keyboard that actually has a keyboard", I clicked the Fdroid link which then makes Fdroid give a toast saying "No such app found". Opening the link in firefox brings me here:

https://f-droid.org/en/packages/io.github.sds100.keymapper.inputmethod.latin/

**Comment by sds100** [comment]
Yeah, I'm waiting for them to approve it. https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7423 A bunch of other new apps also haven't been merged so I'm not sure when it will be added. They were very speedy with Key Mapper so I added the link expecting it to be done.

**Comment by sds100** [comment]
I'm just going to leave it for now because I don't want to go through making a whole new release down the line just to add a link. The 2.1 is still in Beta as well so consider it a beta feature. 😂
