### ISSUE TITLE
Add these actions

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#5]
- torch
- look in lineageos button menus
- go to last app
- kill app
- hotspot, usb/bluetooth tethering
- shutdown phone
- turn screen on/off
- go home/back/recents/menu
- generic camera app shortcut
- start voice search/google assistant.
- start default assistant app
- change particular volume stream. E.g media, ringer etc. 
- all global actions in accessibility service

**Comment by sds100** [comment]
implemented

**Comment by felagund** [comment]
Is the "kill app" something like "close window" (aka ALT+F4 or pressing the x button in the app switcher) or does it really kill the app, so data might by lost?

**Comment by felagund** [comment]
Hm, and why do I not see it on my device? It says "your device doesn't support some actions", might "kill app" be one of them? I forgot it is already 2020 and so thought this was not in a release yet.

**Comment by sds100** [comment]
I haven't added that action yet. My bad, I didn't make it clear which actions I implemented when I closed this issue. Oops.

**Comment by felagund** [comment]
Seems like this is the one to track now: https://github.com/sds100/KeyMapper/issues/114
