### ISSUE TITLE
actions seem too fast to work in chain

### ISSUE THREAD

**Issue by darkenedcolossal** [sds100/KeyMapper#510]
I try to map "vol-down-double-press" on my unrooted phone to open audio recorder app and start recording.
The trigger works.
Opening the recorder app via key mapper took quite long. I tried to open it via "home-button" + "tap audio rec icon screen area" that works sometimes and sometimes i just get to home screen.
I felt like it is all going to fast and I need some timouts. I only found "do nothing" and also tried flashlight on/off to "wait" some time. But it all goes so fast. repeat flashlight on 20 times still takes just a fraction of a second. And you can't add an action a second time to a chain. A restriction I see no benefits for.
I hope you can take the time to respond to some of my issues. Though I does not yet work for me I find Key Mapper very promising and appreciate the work you put into it. Thanks a lot!

**Comment by sds100** [comment]
Hello,

Does the recorder app take a long time to open in certain situations? There is a known issue/feature in Android that apps, which aren't the launcher, can't open or take a long time to open apps while you are on the home screen.

I have just added a feature that allows you to specify the delay between each action in the list. You can try it out in the alpha builds here... https://github.com/sds100/KeyMapper/actions. Every time I push to the repo a new build is made. You can join the Discord server if you want to be notified when a new build comes.

The reason why I don't allow multiple of the same action is so I have some way to uniquely identify the actions in the list. I create an id from all the properties of an action. I will try to change this though...

**Comment by sds100** [comment]
you can now have multiple of the same action in a keymap

**Comment by sds100** [comment]
I'll consider this fixed because no response and multiple of the same action works.
