### ISSUE TITLE
Feature request: Ability to use one key multiple times in sequence mode

### ISSUE THREAD

**Issue by getle87** [sds100/KeyMapper#513]
Hello sds100,

currently I'm looking for a new app to replace the old Xposed Additions (development discontinued). Your app looks very promising for hardware key mapping tasks. There are many other key remapper apps in the store, but no one of them offers the ability to record own key sequences, but in your app this is possible. I only miss one function. Currently, each key can only be used once in recording a sequence trigger (e.g. Vol up + Vol down). Would it be possible to implement the function to use a key multiple times (e.g. Vol Up + Vol Down + Vol Up) to trigger an event? Can the timer (5s) then be reset until no new key is pressed?

current:
![current](https://user-images.githubusercontent.com/58705292/100240634-13fb3580-2f33-11eb-8fe1-ca82346aca38.png)

feature request (screenshot modified):
![feature request](https://user-images.githubusercontent.com/58705292/100240828-4d33a580-2f33-11eb-9255-60dc2a62a097.png)

Sorry for my bad English, it's not my native language.

**Comment by sds100** [comment]
Hello,
I think I can add this but there will be one limitation. If you have a sequence trigger with multiple of the same key, all of those keys must have the same click type (short/long/double press).

E.g you couldn't have `double press volume down` + `single press volume down` but you could have `double press volume down` + `double press volume down`.

**Comment by getle87** [comment]
Hello,

thank you very much for your fast reply. I think this limitation should be no problem.

**Comment by sds100** [comment]
developer todo:
- [ ] write tests
- [ ] allow parallel triggers to have multiple keys with the same keycode but a different device
- [ ] set the click types of all  when setting the clicktype for a key that has duplicates

**Comment by sds100** [comment]
the limitation is now that you can have multiple of the same key **from the same device** as long as they have the same click type. This doesn't affect you but this is information for me.

**Comment by sds100** [comment]
implemented

**Comment by getle87** [comment]
Thank you, the new feature is great. I bought you some coffee on ko-fi.com.
