### ISSUE TITLE
Feature request: option to actually call a number when using direct dial action

### ISSUE THREAD

**Issue by sudomain** [sds100/KeyMapper#516]
Please add an option/checkbox to actually call a number chosen with the direct dial action. I guess it's technically already possible using a direct dial action followed by a tap screen action with a repeat on a delay, but for me the repeat hits the redial button. 

Background: I'm looking to create a SOS calling functionality with triggers from KeyMapper, but for some of more complicated logic I think I need to use KeyMapper to trigger a Termux shortcut instead.

**Comment by sds100** [comment]
Would adding an action to start a phone call work?

**Comment by sudomain** [comment]
That will work. Please :)

**Comment by sds100** [comment]
implemented

**Comment by sudomain** [comment]
Thanks!
