### ISSUE TITLE
Feature request: Triggers/interface with smart watches/heart rate sensors

### ISSUE THREAD

**Issue by sudomain** [sds100/KeyMapper#520]
Some ideas for KeyMapper triggers that can be used with these devices:
* Play/Pause/Next/Previous media buttons (if supported by the device. They're usually software buttons thought)
* Heartrate low
* Heartrate high
* Heartrate hasn't been detected for X seconds/minutes

The world of BT/BLE wearables is a bit like the wild west right now since communication protocols aren't standard, so it might be a better use of dev-time to have the heavy work done in a dedicated app such as [GadgetBridge](https://codeberg.org/Freeyourgadget/Gadgetbridge)

Does KeyMapper have a Broadcast receiver than can be used to trigger keymaps/actions?

Sorry for the rambling of this request. My goal is to have my phone perform actions based on smartwatch sensor values. I realize this may be out of the scope of this project, hence I asked about a broadcast receiver.

**Comment by sds100** [comment]
Yeah, I think it is out of scope like you said since they aren't "buttons". The app would start turning into Tasker. I am happy to add broadcast receiver. Does #490 fulfill this request?

**Comment by sudomain** [comment]
yes please, #490 would be sufficient. I'd then try to get Gadgetbridge to send intents.

**Comment by sds100** [comment]
cool
