### ISSUE TITLE
Bug: Key maps unpressed on other map's activation

### ISSUE THREAD

**Issue by Formedras** [sds100/KeyMapper#580]
**Describe the bug**
"Hold Down" key maps are unpressed when another keymap is activated.

**To Reproduce**
[Keymap Upload - Tetris on Keyboard, zipped for GitHub's pleasure](https://github.com/sds100/KeyMapper/files/5897460/keymaps_20210128-212351-Tetris.zip)
1. Use uploaded keymaps with [Tetris by N3TWORK](https://play.google.com/store/apps/details?id=com.n3twork.tetris). (Triggers are for Das Keyboard X50Q USB keyboard.)
2. Start a game of Ultra (under "Play Tetris") or Marathon ("More Tetris" | "Marathon").
3. Move a tetromino all the way to one side by holding A or D. Then while trying to move it to the opposite side, rotate the piece with Numpad 1 or Numpad 2. Keep holding A or D while/after you press Num1/Num2.
Result: On piece rotation, piece movement stops until key is repressed.

**Expected behavior**
The tetromino should continue moving to the other side of the playfield, even after the rotate key is pressed. If Hold Piece (Numpad 3) is pressed or the tetromino locks, the replacement tetromino should also move to the side of the playfield.

**Smartphone (please complete the following information):**
 - Device: OnePlus 7T (T-Mobile)
 - Android version: Android 10

**Additional context**
Even if this is intentional behavior, it is undesired for most, if not all, games. I can certainly believe that the current behavior has its uses, though. so after fixing, there should be a switch to revert to the current behavior.

**Comment by sds100** [comment]
I think this is because an accessibility service can only tap one coordinate on the screen at a time. Does that sound like the cause?

**Comment by Formedras** [comment]
If that's true about accessibility services, then yeah that would be a likely cause.

If that's the case, then it does seem impossible to properly fix, unless and until Google changes the situation. The closest would be for the software to let go of the hold, do the tap, and then repress the hold again. This would work for something like Tetris, but it may not be good enough for a platformer. Maybe a disclaimer would be in order, to say that the software may not be suitable for gaming due to restrictions given to Accessibility Services.

In the meanwhile, maybe figuring out how Octopus works might be a good idea... if it's even possible.

**Comment by sds100** [comment]
Octopus works by running the whole game as if it were made by Octopus. This is why it needs you to give it all the permissions possible and it needs hacks for Google play authentication to work. I don't know how to do this.
