### ISSUE TITLE
Pressed at the same time doesnt work

### ISSUE THREAD

**Issue by Duvio** [sds100/KeyMapper#588]
The "pressed at the same time" function does not work, when pressing W+A on the keyboard, KeyMapper is supposed to do a specific action, but instead, it just does nothing

My setup is as following:
When W is pressed -> tap (x, y), hold down
When A is pressed -> tap (x, y), hold down
When W+A is pressed at the same time, short -> tap (x, y), hold down, show toast

The W and A configurations work, but when i press W+A at the same time, no action is executed/no toast shows up

This has the effect that i can only move on the horizontal and vertical axis, but not on a diagonal axis

Android 10, rooted
Samsung Galaxy S10 (SM-G973F)

**Comment by sds100** [comment]
Developer TODO
- [ ] create branch
- [ ] write tests
- [ ] rewrite detection algorithm and put under an experimental option in settings
- [ ] enable the option by default on beta, ci and debug builds. Create a VersionUtils class

**Comment by sds100** [comment]
doesn't happen for key code actions so probably an issue with tap coordinate action

**Comment by sds100** [comment]
This works for me in the latest build in GitHub actions. https://github.com/sds100/KeyMapper/actions/runs/839612453

**Comment by sds100** [comment]
no response
