### ISSUE TITLE
"Hold down" and similar disappear when adding a new trigger

### ISSUE THREAD

**Issue by Duvio** [sds100/KeyMapper#594]
**Developer TODO (don't remove)**
- [ ] create new branch
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] delete branch

https://user-images.githubusercontent.com/29256280/107814255-e96e8b00-6d71-11eb-9155-5caa2f9b6f8e.mp4

**Comment by sds100** [comment]
fixed
