### ISSUE TITLE
Constraints for any app playing/not playing media, specific app not playing media

### ISSUE THREAD

**Issue by summersab** [sds100/KeyMapper#598]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name
- [x] write tests before working on feature. put issue number in comment
- [x] update documentation
- [x] delete branch

I'm a fan of the new constraint for "Specific App Playing Media." However, it would be nice to be able to specify:
- Any app playing media
- No apps playing media
- Specific app not playing media

I can accomplish the first by basically creating a constraint for every app currently installed, but if I install new apps, I have to go add a new constraint.

There is no way to specify a "not playing media" constraint (unless I get really creative).

Great app! I'm hoping to use this to fix Android Pie's default to adjust media volume with volume buttons. The previous behavior made much more sense (control system/notification volume by default unless an app is playing media).

**Comment by sds100** [comment]
I'll definitely add this!

**Comment by sds100** [comment]
implemented! :)
