### ISSUE TITLE
Please add a caution message to avoid locking the user when using Screen Pinning mode.

### ISSUE THREAD

**Issue by TheThunderspy** [sds100/KeyMapper#602]
It seems that if you use the "Screen Pinning" Option in Security > Advanced Options when you use "Long Press back button shortcut" you lock the device after dissabling the Fixed Screen Option and rebooting and triggering the action.

Steps to reproduce:
1. Enable Screen Pinning
2. Screw yourself by locking yourself in Settings page lol
4. Disable Screen Pinning option.
4. Reboot
5. Trigger the action, "Long press back button"
6. Enjoy a black screen after trying to unlock device. (In other words, press unlock button, after 0.5 sec it locks again)

The fix is just rebooting the device, disabling the previous action, reboot, enable previous action again.
Everything back to normal, for a moment I just though that I fu### my device, could you please put a warning sign so anyone who cannot reboot by force doesn't have the same problems as I had?

Would be very convenient.

Also your work is very apreciated...!

Edit: The option is not FIxed Screen, it's Screen Pining

**Comment by sds100** [comment]
What is Fixed Screen? I haven't seen this before on stock Android.

**Comment by TheThunderspy** [comment]
It's a weid option which locks the user from the current aplication, requiring long pressing the back button to unlock or introducing a certain password, very stupid option, it can be reversed by rebooting the device.

Nougat 7.0 Android
Bitel B9505 Stock Android + Quick Tiles + SystemUITuner

Here is a screenshot:
![Screenshot_20210222-194101 1](https://user-images.githubusercontent.com/78750328/108788479-11b27280-7546-11eb-8bc1-cfcf72f3b8a9.png)

**Comment by sds100** [comment]
Ohhh, screen pinning. Yeah, i know what you mean. What is the key map that causes the problem? I'm not quite sure what you mean by "long press back button action".

**Comment by TheThunderspy** [comment]
Is this action when triggered, The close vanced thing has nothing to do here, just the action:

![Screenshot_20091231-190541 1](https://user-images.githubusercontent.com/78750328/108870679-5120a380-75c6-11eb-812c-aad1e751cca4.png)

**Comment by sds100** [comment]
Cool, thanks. I'll show a warning that they shouldn't use screen pinning when this key map is enabled whenever they remap their back button.

**Comment by sds100** [comment]
I'll keep this open until I implement it

**Comment by sds100** [comment]
implemented
