### ISSUE TITLE
Document how to remap Bixby button on rooted devices

### ISSUE THREAD

**Issue by andi-at-1** [sds100/KeyMapper#605]
Hello,
I´ve managed to remap the Bixby button on an rooted device, based on this: https://forum.xda-developers.com/t/remap-bixby-manually-using-all-in-one-gestures-bind-to-flashlight-root.3660378/

* Change /system/usr/keylayout/generic.kl:
* 703 Wink changed to 703 DVR (don´t know what DVR means, does nothing stock...)
* reboot
* now the key-press-event will show up in your app and i´m happily toggling my flashlight :-) 

maybe you could add that process of editing the genetic.kl to make that work automatic on rooted devices?

regards, andi

**Comment by sds100** [comment]
Hi, that would work in theory but I don't want to attempt to automate modifying a very important file on people's devices. 😄

**Comment by andi-at-1** [comment]
Okay that sounds like an argument :-D But mabe you could notice that possibility in the app description and give a link to a short howto? Or just point out the search term to let people find out themselves... Cuz that limitation is just not correct!

regards

**Comment by sds100** [comment]
I'll add your guide to the website! And will add a special mention in the app description. Thanks!

**Comment by sds100** [comment]
implemented
