### ISSUE TITLE
Multiple language support

### ISSUE THREAD

**Issue by cosmostronomer** [sds100/KeyMapper#609]
Hi,

Thank you for the great work! What an amazing work :)
I have noticed that you have added multiple language support last july.
I could not find the settings to enable such feature.
Do I have to download the gui app?

Best wishes,
cosmostronomer

**Comment by sds100** [comment]
Hi!
Do you mean that the app treats non-English keyboards better? If so then there shouldn't be anything that you need to do.
The app hasn't been translated if you were wondering about that.

**Comment by cosmostronomer** [comment]
I mean I cannot change language using the designated key. There is a 'language switch' key on my keyboard which doesn't work when I switch to key mapper basic input method.

**Comment by sds100** [comment]
Try using the Key Mapper GUI Keyboard. I'm not 100% sure how that language key works. Does it change the language of the keyboard in the Android settings?

**Comment by cosmostronomer** [comment]
I am also not certain how it works. It probably works as you said. It's
like the language change key with globe icon on software keyboard but it's
on hardware.

I tried using GUI keyboard and there are two problems. One is that there is
no language support for Korean, Chinese, Japanese. I could not find them on
language list. Two is that even if I try with supported languages, I still
cannot change language using the hardware key.

The key mapper app registers the key correctly as 'Language Switch (Tab S7+
Book Cover Keyboard)' and shows toast message when pressed. But it does
nothing. Is there a way to map the hardware key to language change key
which works just fine on any software keyboard?

>

**Comment by sds100** [comment]
The GUI keyboard doesn't support languages which don't use the Latin script. Which keyboard do you usually use? Can you send a screen recording of what the language switch key does when you aren't using Key Mapper? What are you using Key Mapper for?

**Comment by cosmostronomer** [comment]
Hi,

Please find the attached screen recording. I was using samsung default keyboard but google keyboard (GBoard) also works fine.
https://user-images.githubusercontent.com/34349131/110261701-909eb500-7ff4-11eb-8656-58d6972142e4.mp4
I wanted to use key mapper for remapping hotkeys which cannot be changed on samsung devices. For example, pressing Cmd + P opens youtube music which I don't want.

**Comment by sds100** [comment]
Does the popup message that tells you which language it's switch to show when you are using a Key Mapper keyboard?

I setup multiple languages for a physical keyboard in the Android settings. I don't have a language switch key but pressing the Ctrl+Space bar shortcut to switch languages worked when I used the GUI Keyboard and Key Mapper.

Can you send a backup of all your key maps by holding down on a key map on the home screen and then selecting all, then pressing back up.

**Comment by cosmostronomer** [comment]
Does the popup message that tells you which language it's switch to show when you are using a Key Mapper keyboard?
-No it doesn't. The language change key doesn't do anything when using the key mapper keyboard.

I setup multiple languages for a physical keyboard in the Android settings. I don't have a language switch key but pressing the Ctrl+Space bar shortcut to switch languages worked when I used the GUI Keyboard and Key Mapper.
-That is interesting. Ctrl+Space or Shift+Space or Shift+Alt none of the shortcuts work for me when I use GUI keyboard. They do work with samsung keyboard.

Can you send a backup of all your key maps by holding down on a key map on the home screen and then selecting all, then pressing back up.
-My key maps have constraints so they should not matter. The issue persists even when I disable them all.
[keymaps_20210309-002246.zip](https://github.com/sds100/KeyMapper/files/6102372/keymaps_20210309-002246.zip)

**Comment by cosmostronomer** [comment]
My Android settings:
![KakaoTalk_20210309_003857115](https://user-images.githubusercontent.com/34349131/110343527-ebc1bd80-806f-11eb-8e71-b92ca63a3aeb.jpg)
![KakaoTalk_20210309_003856859](https://user-images.githubusercontent.com/34349131/110343536-ecf2ea80-806f-11eb-870b-a9b658031518.jpg)
![KakaoTalk_20210309_003856988](https://user-images.githubusercontent.com/34349131/110343539-ecf2ea80-806f-11eb-9efd-7ec5ed83fae3.jpg)

**Comment by sds100** [comment]
Are you on Android 11?

**Comment by cosmostronomer** [comment]
yes

2021년 3월 9일 (화) 오전 1:33, Seth <notifications@github.com>님이 작성:

**Comment by sds100** [comment]
Hmm, does turning off the Key Mapper accessibility service but still using the GUI Keyboard fix the problem?

**Comment by cosmostronomer** [comment]
unfortunately not.

2021년 3월 9일 (화) 오전 1:35, Seth <notifications@github.com>님이 작성:

**Comment by sds100** [comment]
how do you select multiple languages for a physical keyboard on a Samsung device? I can do it on my AOSP phone but it isn't clear how to do it on OneUI.

**Comment by cosmostronomer** [comment]
Although this does not explain why you can use hotkeys to change language, but the hardware key I have is 'GroupNext' which does have an android key code (204). [Key values](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values)
![image](https://user-images.githubusercontent.com/34349131/110353393-5d066e00-807a-11eb-843a-54819d2c930a.png)

how do you select multiple languages for a physical keyboard on a Samsung device? I can do it on my AOSP phone but it isn't clear how to do it on OneUI.
-I add languages to software keyboard(samsung keyboard or google keyboard). However, it seems like only English, Korean, Japanese, Chinese are supported. Other Latin languages can be setup and switched to (hotkeys work), but typing on hardware keyboard shows qwerty alphabet.

**Comment by sds100** [comment]
![Screenshot_20210308-171847_Settings.png](https://user-images.githubusercontent.com/16245954/110357182-eb570180-8032-11eb-9008-5f686cbd6bc0.png)![Screenshot_20210308-172159_Settings.png](https://user-images.githubusercontent.com/16245954/110357185-ec882e80-8032-11eb-933d-5dd521ffec9e.png)![Screenshot_20210308-171922760.jpg](https://user-images.githubusercontent.com/16245954/110357193-edb95b80-8032-11eb-89e8-69d3184e3dc0.jpg)![Screenshot_20210308-172218529.jpg](https://user-images.githubusercontent.com/16245954/110357197-ef831f00-8032-11eb-9113-7d1497f81e51.jpg)

**Comment by sds100** [comment]
Can you send a screen recording? 😂 I can't figure out how to do it! The UI is completely different.

**Comment by cosmostronomer** [comment]
for samsung keyboard,
https://user-images.githubusercontent.com/34349131/110357778-00f21880-807f-11eb-995d-168b2ba15311.mp4
for google keyboard,
https://user-images.githubusercontent.com/34349131/110357834-10716180-807f-11eb-87cb-9b2ad1b935c4.mp4

**Comment by sds100** [comment]
Hmm, I don't have any of that (except the Gboard settings but that also doesn't do anything). Since I can't test it on my Samsung device and I can switch languages on my AOSP phone then I'm not sure where the issue is. Do you have another non-Samsung Android device or any kind?

**Comment by cosmostronomer** [comment]
No I don't and the keyboard I am using uses proprietary POGO keyboard for Galaxy Tab s7+ so unless I get a bluetooth keyboard I won't be able to test even if I had another device. :(

Can you not add and switch languages using GBoard?

**Comment by sds100** [comment]
I can't make the physical keyboard settings recognise multiple languages from gboard either. It works on my AOSP phone.
