### ISSUE TITLE
Key with modifiers also activate the single key mapping.

### ISSUE THREAD

**Issue by cosmostronomer** [sds100/KeyMapper#610]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Describe the bug**
Enter -> Alt + Enter
Alt + Enter -> Enter

Setting two mappings and pressing Alt+Enter activates both.
Alt + Enter -> Enter + Alt + Enter

**Expected behavior**
Enter -> Alt + Enter should not be called when Alt + Enter is pressed.

**Smartphone (please complete the following information):**
 - Device: [Galaxy Tab s7+ 5G]
 - Android version: [Android 11]

**Comment by sds100** [comment]
does this happen on the latest 2.2.0 release?

**Comment by cosmostronomer** [comment]
Oh no it doesn't. I wasn't aware that there is new update! Thanks

**Comment by sds100** [comment]
cool!
