### ISSUE TITLE
Record Trigger about Keycode_DPAD_up&down&left&right

### ISSUE THREAD

**Issue by tiandongxv** [sds100/KeyMapper#631]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Describe the bug**

Hi, when I connect to the Bluetooth Gamepad, On Record Trigger, the direction key(Keycode_DPAD_up&down&left&right) cannot be recognized, but it can be add on the action interface(From key by clicking the key).

Ps:Keycode_DPAD_up&down&left&right keycode:19&20&21&22

Please add this function. thank you!
**Smartphone (please complete the following information):**
 - Device: [Boox nova2]
 - Android version: [Android 9]
 - App version:  [v2.2]

**Comment by sds100** [comment]
Hello,
Accessibility services aren't when DPAD buttons are pressed but input method services are. I've already created an issue https://github.com/sds100/KeyMapper/issues/491.
