### ISSUE TITLE
Update on F-Droid please

### ISSUE THREAD

**Issue by sudomain** [sds100/KeyMapper#633]
Sorry if this isn't the preferred way to request this (different devs have difference preferences on this). 

The last update on F-Droid is version 2.2.0-beta.1. I have an issue with they app crashing when trying to trying to create a widget. I didn't want to open an official issue on this since I'm running an outdated version with "beta" in the name. Please update on F-Droid.

**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and squash
- [ ] delete branch

**Comment by sds100** [comment]
yeah, i've noticed. i'm not sure why there are issues. Do you know if there is somewhere that f-droid logs why an app couldn't be built?

**Comment by sds100** [comment]
i think my half-finished manual fastlane implementation to automate releases to the play store messed it up. i'll try switching to this release automation tool https://github.com/Triple-T/gradle-play-publisher which is also supported by F-Droid. i think this is better than fastlane for my use case.

**Comment by sudomain** [comment]
I'm not very familiar with F-Droid's update procedures, but I [opened an issue](https://gitlab.com/fdroid/fdroiddata/-/issues/2357) with their fdroiddata repo requesting an update.

**Comment by sds100** [comment]
Cool, thanks!

**Comment by sudomain** [comment]
Looks like they updated the metadata and iirc that means  the app update will hit the store in a couple days. I'll leave this open since I'm not sure if you want it open as a reminder to switch to that release automation tool. 

Thanks again for the great app.

**Comment by sds100** [comment]
fixed
