### ISSUE TITLE
Add action to play some sound

### ISSUE THREAD

**Issue by tardyp** [sds100/KeyMapper#652]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name. => origin/feature/652-play-sound-action
- [x] write tests before working on feature. put issue number in comment
- [x] update documentation
  - Explain the behaviour in Notes
- [x] let translators in Discord server know there are strings to translate
- [x] squash and merge
- [x] delete branch
- [x] update library credits

**Notes**
- [x] use Accessibility stream?
- [x] only enable accessibility stream if a key map that requires it is enabled and the mappings are unpaused
- [x] copy file to Key Mapper's private folder??
- [x] create SoundsManager that
  - has method for saving sounds
  - method for retrieving sounds
  - ~~Automatically store hashes of new files and don't save duplicates of files.~~
    - ~~create separate data store to preferences~~
    - ~~the hashes should not be saved with the back ups~~
```
MessageDigest digest = MessageDigest.getInstance("SHA-256");
byte[] hash = digest.digest(text.getBytes(StandardCharsets.UTF_8));
```
- [x] back up sound files with key maps?? use zip4j to back up to a zip file https://github.com/srikanth-lingala/zip4j
- [x] automatically use the sound files name
- [x] show an option when creating sounds to select an existing sound or a new one.
- [x] ~~store file hash in action~~
- [x] do restoring
- [x] ensure back ups without being in a zip folder are still supported
- [x] show error if failed to create sound action
- [x] show action error if sound doesnt exist
- [x] always back up all sounds incase the user wants to save a sound for later. Show a button to delete sounds in the settings.
- [x] ~~automatically delete sounds when they aren't needed by key maps any more.~~ The user might want to use a sound later.
- [x] stop playing when key maps are paused
- [x] do TODO items

My use case would be to have a virtual bike bell.

Goal is to use one of those:
![image](https://user-images.githubusercontent.com/109859/116005244-65a10c80-a606-11eb-8ceb-e7fc69591e5b.png)
which is just a one button bluetooth keyboard that sends vol-up keycode.

and make my EUC bell when I click the button

EUC is that:
![image](https://user-images.githubusercontent.com/109859/116005134-ec091e80-a605-11eb-8b2c-f347d69c0834.png)

The EUC can connect to android phone as a a2dp speaker, so the only thing remaining is to map the bluetooth keyboard to playing a sounds. I guess KeyMapper is the nearest thing available to do that.
I already recognise the bluetooth button, but it is missing a play sound feature.
The play media is for me not an option as it would require changing the current music with a honk sound before the ride. pretty impractical.

**Comment by sds100** [comment]
Wow, that's a cool use case! I'll investigate what I can do...

**Comment by sds100** [comment]
@tardyp did you manage to fix the issue with getting your bluetooth keyboard to turn your phone's screen on? Have you tried turning off "pocket mode" or "always on display" or "ambient display"?

**Comment by tardyp** [comment]
@sds100 No I wasn't able to make it work, I am not aware of those features, but those sound like a good trail. let me know if you have a build I want to test.

**Comment by tardyp** [comment]
on my mac m1, it is a bit more annoying to compile, as it requires some patches. I will submit them soon..

anyways, your version worked like a charm for me.

On the first time when I selected the play sound action, I got a animated load icon  that never ended until I click on the back button. Then on second time, the choose sound file button did show up.

I wasn't able to reproduce the problem.


halas, when I put my phone in the pocket. after about 30s of inactivity while in the pocket, then the bluetooth button will not work anymore.
I need to put the phone away from the pocket and wake it up for the app to work again.

I couldn't find any option in the pixel 4a such as pocket mode :-/

**Comment by sds100** [comment]
"On the first time when I selected the play sound action, I got a animated load icon that never ended until I click on the back button. Then on second time, the choose sound file button did show up.". Yeah, this is an issue right now but it will be fixed when I completely redo the choose action screen. There are way too many tabs right now. see #603

Have you looked into the bluetooth button issue online? I wonder if Key Mapper can keep a wake lock or something to force your device to not go into idle. It will drain battery much faster though.

**Comment by tardyp** [comment]
I could find this unanswered question, but nothing much more.
https://stackoverflow.com/questions/43231194/android-wake-up-app-on-bluetooth-keyboard-key-pressed

I think the wakelock must be the only solution for this.

We might have a "keep-awake" flag on the trigger:
If the trigger that is associated with a bluetooth keyboard, and the bluetooth keyboard is connected, then keep the wakelock until the bluetooth keyboard is disconnected.

**Comment by sds100** [comment]
[keymapper-wakelock-test.zip](https://github.com/sds100/KeyMapper/files/6737229/keymapper-wakelock-test.zip)

Try this apk that acquires a wake lock forever once the accessibility service is started. I just want to see if a wake lock will fix the issue at all.

**Comment by sds100** [comment]
implemented

**Comment by tardyp** [comment]
@sds100 I tested your wakelock apk. I don't see any change. When I put the phone in the pocket, then after a few minutes the bluetooth button stops triggering any action.

After a while. I can see the bluetooth button might be itself entering a low power mode.
The first time I push button. I got a long led blink that I think it bluetooth reconnection.

then while my phone is still in the pocket, the subsequent push button I got short blinks, but no sound.
As soon as I put the phone out of the pocket, the sound works.

When I look at the log, I only see the events from after the phone is out of the pocket.

**Comment by sds100** [comment]
Yeah, that is what I thought. I have created an apk that logs whenever a bluetooth device is connected/disconnected. That way we can see if it is actually completely disconnecting/reconnecting or Android is just ignoring the inputs. 
[keymapper-2.4.0-alpha-debug.zip](https://github.com/sds100/KeyMapper/files/6741295/keymapper-2.4.0-alpha-debug.zip)
