### ISSUE TITLE
Multi gamepads mapping issue

### ISSUE THREAD

**Issue by godzellax** [sds100/KeyMapper#660]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Describe the bug**

The app working fine and mapped buttons detected on many games as a virtual device. However, all my mapped devices detected as one virtual device on all working games so I cannot make multi devices to work together to play multiplayer games. In other words, all connected and mapped devices whether gamepads or keyboards function as one and I mean literally one virtual device and all working games see it as one connected device, please fix it.

Thank you for your efforts and may God bless you,

**To Reproduce**
After mapping more than one device, all mapped keys will be detected by other apps/games as one virtual device.

**Expected behavior**
Every mapped gamepad should detected as a device seperately.

 - Device: Samsung Galaxy Note 4 sm-n910c
 - Android version: 6.0

**Comment by sds100** [comment]
Hello,
Pause all your key maps.
If you turn the accessibility service off does the issue go away?
If you then turn it back on, without unpausing your key maps, does the issue come back?

**Comment by sds100** [comment]
Ignore that message, I misunderstood what you're asking. I think you want to create an action under the Key Event tab and then select the device that you want to input from.

**Comment by godzellax** [comment]
I hope you understand me, forgive me because of my English.

Would you please tell if you can please fix the issue.

Your app is the best and the only one i found that works to map all hard keys without root but because of the issue I'm facing i cannot play any multiplayer games because all attached devices, games will see it as player 1 and no way to play 2 players or more together.

I tried many games and all the same will see all attached and mapped devices by you app as one attached device.



Sent from my Samsung device


-------- Original message --------
From: Seth ***@***.***>
Date: 04/05/2021 6:00 p.m. (GMT+02:00)
To: sds100/KeyMapper ***@***.***>
Cc: godzellax ***@***.***>, Author ***@***.***>
Subject: Re: [sds100/KeyMapper] Multi gamepads mapping issue (#660)


Ignore that message, I misunderstood what you're asking. I think you want to create an action under the Key Event tab and then select the device that you want to input from.

**Comment by sds100** [comment]
I think you want to create an action under the Key Event tab instead of the Key Code one and then select the device that you want to input from. Your English is great!

**Comment by godzellax** [comment]
I'll try and let you know.

Thank you so much Sir



Sent from my Samsung device


-------- Original message --------
From: Seth ***@***.***>
Date: 04/05/2021 6:29 p.m. (GMT+02:00)
To: sds100/KeyMapper ***@***.***>
Cc: godzellax ***@***.***>, Author ***@***.***>
Subject: Re: [sds100/KeyMapper] Multi gamepads mapping issue (#660)


I think you want to create an action under the Key Event tab instead of the Key Code one and then select the device that you want to input from. Your English is great!

**Comment by godzellax** [comment]
Oh my god. You saved my day!!!

I still have no idea whats the difference between keycode and keyevent if you please explain it to me.

I just have one more question please, why some games will not detect keyboard as gamepad if you map some keyboard keys to gamepad keys.
Not with your app only, its happening with all similar of your app also.



Sent from my Samsung device


-------- Original message --------
From: Fadi Bitar ***@***.***>
Date: 04/05/2021 6:58 p.m. (GMT+02:00)
To: sds100/KeyMapper ***@***.***>, sds100/KeyMapper ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [sds100/KeyMapper] Multi gamepads mapping issue (#660)

I'll try and let you know.

Thank you so much Sir



Sent from my Samsung device


-------- Original message --------
From: Seth ***@***.***>
Date: 04/05/2021 6:29 p.m. (GMT+02:00)
To: sds100/KeyMapper ***@***.***>
Cc: godzellax ***@***.***>, Author ***@***.***>
Subject: Re: [sds100/KeyMapper] Multi gamepads mapping issue (#660)


I think you want to create an action under the Key Event tab instead of the Key Code one and then select the device that you want to input from. Your English is great!

**Comment by sds100** [comment]
when you create a "key code" action Key Mapper is creating a key event action behind-the-scenes but they only thing it configures is the key code. it is basically a shortcut for creating a simple Key Event action.

Games usually only detect gamepad keys if they are coming from a real game pad

**Comment by godzellax** [comment]
Thank you so much Sir. You are so cute.

I only hope if you add profiles to your app so we can select between them before launching the games or even you can make it auto profile per game if possible.



Sent from my Samsung device


-------- Original message --------
From: Seth ***@***.***>
Date: 04/05/2021 7:33 p.m. (GMT+02:00)
To: sds100/KeyMapper ***@***.***>
Cc: godzellax ***@***.***>, Author ***@***.***>
Subject: Re: [sds100/KeyMapper] Multi gamepads mapping issue (#660)


when you create a "key code" action Key Mapper is creating a key event action behind-the-scenes but they only thing it configures is the key code. it is basically a shortcut for creating a simple Key Event action.

Games usually only detect gamepad keys if they are coming from a real game pad

**Comment by sds100** [comment]
This is a planned feature! #320

**Comment by godzellax** [comment]
Thank you Sir and sorry for interrupting you.



Sent from my Samsung device


-------- Original message --------
From: Seth ***@***.***>
Date: 04/05/2021 7:49 p.m. (GMT+02:00)
To: sds100/KeyMapper ***@***.***>
Cc: godzellax ***@***.***>, Author ***@***.***>
Subject: Re: [sds100/KeyMapper] Multi gamepads mapping issue (#660)


This is a planned feature! #320<https://github.com/sds100/KeyMapper/issues/320>
