### ISSUE TITLE
Enter text not working

### ISSUE THREAD

**Issue by GL513** [sds100/KeyMapper#677]
Although the log appears to say its all fine, keymapper never enters text ("Type text" action) into anything.

Here is my log:

'15:09:24.184  Down KEYCODE_A, key code: 29, device name: Bluetooth Keyboard, descriptor: 92cfe120b30c4f8f221ede28244100b4ab55beb9, device id: 11, is external: true, meta state: 0, scan code: 30
15:09:24.184  Down KEYCODE_A - consumed: true, key code: 29, device name: Bluetooth Keyboard, descriptor: 92cfe120b30c4f8f221ede28244100b4ab55beb9, device id: 11, is external: true, meta state: 0, scan code: 30
15:09:24.184  Up KEYCODE_A, key code: 29, device name: Bluetooth Keyboard, descriptor: 92cfe120b30c4f8f221ede28244100b4ab55beb9, device id: 11, is external: true, meta state: 0, scan code: 30
15:09:24.184  Performed action TextAction(text=‎Test), input event type: DOWN_UP, key meta state: 0
15:09:24.184  Up KEYCODE_A - consumed: true, key code: 29, device name: Bluetooth Keyboard, descriptor: 92cfe120b30c4f8f221ede28244100b4ab55beb9, device id: 11, is external: true, meta state: 0, scan code: 30`

**Comment by sds100** [comment]
I can't reproduce this issue. What if you try the latest alpha build in #testing-builds in the discord?

**Comment by GL513** [comment]
> I can't reproduce this issue. What if you try the latest alpha build in #testing-builds in the discord?

Unfortunately, it still doesnt work... :/

**Comment by sds100** [comment]
Can you send a back up of your key maps

**Comment by sds100** [comment]
Fixed
