### ISSUE TITLE
Headset key not working when screen is locked and off

### ISSUE THREAD

**Issue by georgeabr** [sds100/KeyMapper#679]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Describe the bug**
The remote control button on my headphones, Sony MDREX650APT, does not work as expected when the smartphone is locked, and the screen is off.

**To Reproduce**
The headphones have one button, which I have mapped to raise the volume on a long single press, and lower it, on double press.
On a short press, the mapping is to play/pause current track.
These mappings work as expected in YouTube Music, when screen is awake, whether the phone is locked or not.
The mappings do not work, if the screen is locked and off (a long single press does nothing, for example).

**Expected behavior**
A double press should lower the volume, a long press should raise the volume, even when the screen is locked and off.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7
 - Android version: Android 8 (Samsung)

I have given the app all the required 5 permissions, including the DND and WRITE_SECURE_ENABLED permissions.

Below is the config file:
{"device_info":[],"fingerprint_swipe_down":{"action_list":[],"constraints":[],"constraint_mode":1,"extras":[],"flags":0,"enabled":true},"fingerprint_swipe_left":{"action_list":[],"constraints":[],"constraint_mode":1,"extras":[],"flags":0,"enabled":true},"fingerprint_swipe_right":{"action_list":[],"constraints":[],"constraint_mode":1,"extras":[],"flags":0,"enabled":true},"fingerprint_swipe_up":{"action_list":[],"constraints":[],"constraint_mode":1,"extras":[],"flags":0,"enabled":true},"keymap_list":[{"actionList":[{"data":"volume_up","extras":[],"flags":5,"type":"SYSTEM_ACTION","uid":"0d178bdb-db91-46bb-82f2-bc348a3b1bd4"}],"constraintList":[],"constraintMode":1,"flags":0,"id":1,"isEnabled":true,"trigger":{"extras":[],"flags":0,"keys":[{"clickType":1,"deviceId":"io.github.sds100.keymapper.THIS_DEVICE","flags":0,"keyCode":79,"uid":"68fe3d1e-3fb1-45ec-b107-04ccb2a7d332"}],"mode":2},"uid":"4ada5109-9efe-4cba-bfb3-7b61a8a9dde0"},{"actionList":[{"data":"volume_down","extras":[],"flags":1,"type":"SYSTEM_ACTION","uid":"717963c5-73d3-4507-960f-7410f8842c7c"}],"constraintList":[],"constraintMode":1,"flags":0,"id":2,"isEnabled":true,"trigger":{"extras":[],"flags":0,"keys":[{"clickType":2,"deviceId":"io.github.sds100.keymapper.THIS_DEVICE","flags":0,"keyCode":79,"uid":"cfd73c02-1c95-40b6-aa4b-0e69bb0165a7"}],"mode":2},"uid":"0f7ccee0-88f2-4f9a-8490-8783622bb50a"},{"actionList":[{"data":"play_pause_media","extras":[],"flags":0,"type":"SYSTEM_ACTION","uid":"ca1d91e5-f19d-4737-a9ce-0467fb2dd1c6"}],"constraintList":[],"constraintMode":1,"flags":0,"id":3,"isEnabled":true,"trigger":{"extras":[],"flags":0,"keys":[{"clickType":0,"deviceId":"io.github.sds100.keymapper.THIS_DEVICE","flags":0,"keyCode":79,"uid":"4fd90440-9cc0-44e6-8c00-15ad00e7d3a8"}],"mode":0},"uid":"1775dd8c-7faa-4d44-9e3a-6d58308e157a"}]}

**Comment by sds100** [comment]
Yeah, this is a limitation in Android. There is no fix for this unless you're rooted. If you're rooted I will have to add support for your button specifically. But even this isn't very reliable and on some devices doesn't work well.
