### ISSUE TITLE
how do i unlock my phone with out a keyboard i think u guys shuold add a feature that well uh disables key mapper when u restart ur phone and plz help me fix this

### ISSUE THREAD

**Issue by xxxxxxzzxzsa** [sds100/KeyMapper#681]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Describe the bug**

**To Reproduce**

Upload a backup of your keymaps. (Follow the guide here.)[https://sds100.github.io/KeyMapper/user-guide/backup-restore]

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T]
 - Android version: [e.g. Android 10]

**Additional context**

**Comment by sds100** [comment]
Install the Key Mapper GUI Keyboard to fix this problem. You will just have to remember to not use the Key Mapper Basic Input Method
