### ISSUE TITLE
Acts on screenshot

### ISSUE THREAD

**Issue by GL513** [sds100/KeyMapper#683]
When i take a screenshot, the app will ocassionally trigger, making my keymap that toggles the notification bar go off at the same time as the screenshot.

This may be different for other devices other than samsung, since for samsung, you only have to tap vol up+pwr to take a screenshot, where as on most other devuces require a press-hold.

Unfortunately, i cant determine when this will happen, but if this happens again i will append the log to this.

Update...
It appears that it triggers after the buttons are actually pressed. In this log, it has the down-up sequence before the screenshot.

Here is the log

07:11:47.158 Down KEYCODE_VOLUME_DOWN, key code: 25, device name: qpnp_pon, descriptor: fb60d4f4370f5dbe8267b63d38dea852987571ab, device id: 5, is external: false, meta state: 0, scan code: 114

07:11:47.160 Down KEYCODE_VOLUME_DOWN - consumed: true, key code: 25, device name: qpnp_pon, descriptor: fb60d4f4370f5dbe8267b63d38dea852987571ab, device id: 5, is external: false, meta state: 0, scan code: 114

07:11:47.667 Performed action SimpleSystemAction(id=TOGGLE_NOTIFICATION_DRAWER), input event type: DOWN_UP, key meta state: 0

This is the behaviour I expect though

07:16:40.596  Down KEYCODE_VOLUME_DOWN, key code: 25, device name: qpnp_pon, descriptor: fb60d4f4370f5dbe8267b63d38dea852987571ab, device id: 5, is external: false, meta state: 0, scan code: 114
07:16:40.597  Down KEYCODE_VOLUME_DOWN - consumed: true, key code: 25, device name: qpnp_pon, descriptor: fb60d4f4370f5dbe8267b63d38dea852987571ab, device id: 5, is external: false, meta state: 0, scan code: 114
07:16:41.109  Performed action SimpleSystemAction(id=TOGGLE_NOTIFICATION_DRAWER), input event type: DOWN_UP, key meta state: 0
07:16:41.701  Up KEYCODE_VOLUME_DOWN, key code: 25, device name: qpnp_pon, descriptor: fb60d4f4370f5dbe8267b63d38dea852987571ab, device id: 5, is external: false, meta state: 0, scan code: 114
07:16:41.702  Up KEYCODE_VOLUME_DOWN - consumed: true, key code: 25, device name: qpnp_pon, descriptor: fb60d4f4370f5dbe8267b63d38dea852987571ab, device id: 5, is external: false, meta state: 0, scan code: 114

**Comment by sds100** [comment]
see if this still happens in the latest testing build

**Comment by GL513** [comment]
> see if this still happens in the latest testing build

Yeah, it still is :/

**Comment by sds100** [comment]
Everything looks fine in the Key Mapper log. If the system is telling Key Mapper that the buttons are being pressed then that's fine. From Key Mappers perspective the system isn't doing anything with the button presses

**Comment by sds100** [comment]
Taking a screenshot on stock Android (vol down + power) doesn't interfere with it.

**Comment by sds100** [comment]
This doesn't sound like something Key Mapper can fix.
