### ISSUE TITLE
Ability to highlight (select) logs

### ISSUE THREAD

**Issue by GL513** [sds100/KeyMapper#684]
**TODO**
- [x] Fix lag opening log screen when the log is huge

This is very helpful for copy and pasting, so we dont have to copy and paste the whole log and have to delete a bunch of it.

**Comment by sds100** [comment]
Yeah, good idea

**Comment by sds100** [comment]
implemented

**Comment by sds100** [comment]
super super laggy by using textview. revert to recycler view. Implement this behaviour https://github.com/MFlisar/DragSelectRecyclerView

**Comment by sds100** [comment]
implemented
