### ISSUE TITLE
When input device disconnected stop current running keymaps input from device

### ISSUE THREAD

**Issue by GL513** [sds100/KeyMapper#690]
This is mostly for saftey reasons. Mabey think about not accepting input from that device either when its not connected, as it may save battery life.

**Comment by sds100** [comment]
I'm not sure what you mean. Key maps that remap a disconnected device should be ignored?

**Comment by GL513** [comment]
> I'm not sure what you mean. Key maps that remap a disconnected device should be ignored?

Yes, but also if there is a keymap that is set to repeat, and is triggered before the device disconnects, and then it does disconnect, the repeat should be stopped.

**Comment by sds100** [comment]
I guess that is a bug but it is unlikely to happen by accident and if you set up a key map to repeat until pressed again then it is doing what it says by repeating until pressed again. If you disconnect the device then it is the user's fault that they can't press the buttons again.

**Comment by sds100** [comment]
from what i understand this isn't worth the work/bugs to implement
