### ISSUE TITLE
Invalid link in 2.2 release details about breaking changes

### ISSUE THREAD

**Issue by bahusoid** [sds100/KeyMapper#703]
https://github.com/sds100/KeyMapper/releases/tag/v2.2.0

> Key Mapper action shortcuts work completely differently. See https://docs.keymapper.club/user-guide/triggers/#trigger-from-other-apps-230

I guess it should be: 
https://docs.keymapper.club/user-guide/keymaps.html#trigger-from-other-apps-230

**Comment by sds100** [comment]
i actually have a redirect link for it incase the place of it changes, i'll use that. https://docs.keymapper.club/KeyMapper/redirects/trigger-by-intent

**Comment by bahusoid** [comment]
> i'll use that. https://docs.keymapper.club/KeyMapper/redirects/trigger-by-intent

Hm. It gives me 404 not found.. Same as https://docs.keymapper.club/user-guide/triggers/#trigger-from-other-apps-230
