### ISSUE TITLE
Feature request: KeyMapper Keyboard fork of "Hacker's Keyboard"

### ISSUE THREAD

**Issue by sudomain** [sds100/KeyMapper#716]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name
- [x] write tests before working on feature. put issue number in comment
- [x] update documentation
- [ ] squash and merge
- [ ] delete branch

Per the conversation on Discord: please make a KeyMapper compatible fork of [Hacker's Keyboard](https://github.com/klausw/hackerskeyboard). This will allow me to use KeyMapper with a keyboard that has `Ctrl`, `Alt`, and arrow keys.(

**Comment by sds100** [comment]
you can download it here https://github.com/sds100/KeyMapperHackersKeyboard/releases/tag/v1.41.2

**Comment by sudomain** [comment]
Thanl you!
