### ISSUE TITLE
Use `disableSelf()` to stop accesibility service from notification

### ISSUE THREAD

**Issue by Susko3** [sds100/KeyMapper#717]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name
- [x] write tests before working on feature. put issue number in comment
- [x] update documentation
- [x] squash and merge
- [x] delete branch

https://developer.android.com/reference/android/accessibilityservice/AccessibilityService.html#disableSelf()
Only applicable in API level 24 and up.

The stop service button in the notification:

![image](https://user-images.githubusercontent.com/16479013/123545839-6d8e4180-d75a-11eb-860d-c16025e9ffd7.png)

**Comment by sds100** [comment]
implemented
