### ISSUE TITLE
Flashlight on/off constraint

### ISSUE THREAD

**Issue by Susko3** [sds100/KeyMapper#722]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name
- [x] write tests before working on feature. put issue number in comment
- [x] update documentation
- [x] squash and merge
- [x] delete branch

A pair of constraints for whether the flashlight is on or off.
Should provide options for both front and back flashlight, to be in line with the flashlight action.

**Comment by sds100** [comment]
implemented
