### ISSUE TITLE
make it much easier to report bugs

### ISSUE THREAD

**Issue by sds100** [sds100/KeyMapper#728]
People press copy and it is often too long to paste into messaging apps.
https://developer.android.com/training/sharing/send

**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name
- [x] write tests before working on feature. put issue number in comment
- [x] create a slides screen that goes through each step to solve the issue so the user doesn't have to jump around between websites and within Key Mapper. 
  - [x] don't show this screen on debug builds.
  - [x] always show button to skip.
  - [x] Screen 1: Dialog. telling them what has gone wrong. Have you followed the guide at dontkillmyapp.com before? Yes or No
  - [x] Screen 2 (if no): tell them to follow the guide at dontkillmyapp.com for their device and then come back to Key Mapper
  - [x] Screen 2: yellow with bug icon. (if yes): If following the guide at dontkillmyapp.com doesn't fix the problem then it might be a bug in Key Mapper. Show a button to create a bug report that allows them to choose where it is saved. Automatically progress to the next slide when it has been created. Hide next button
  - [x] Screen 3: How do you want to send it? Make sure to attach the bug report to the message. Discord, GitHub or Email. Tapping on them should open the server, create a new bug issue and start an email.
  - [x] Screen 4 (for both paths): restart the accessibility service and hopefully it doesnt crash again.
- [x] automatically show the screen when Key Mapper is opened and the accessibility service is crashed.
~~- [ ] share button in logging screen.~~
- [x] Turn send feedback menu button into "report bug" and give it a bug icon.
- [x] Report bug button should create a zip with their mappings, log, device information and key mapper version.
- [x] when failing to record a trigger because the accessibility service is crashed, show the same dialog explaining how to fix the problem as on the home screen.
- [x] Update steps in discord server for optimisation
- [x] update report issues page in documentation
- [x] squash and merge
- [x] delete branch

**Comment by GL513** [comment]
Possibly also add a heyoerlink to the [new issue page](https://github.com/sds100/KeyMapper/issues/new) for easy access?

**Comment by sds100** [comment]
> Possibly also add a hyperlink to the [new issue page](https://github.com/sds100/KeyMapper/issues/new) for easy access?

Yeah

**Comment by sds100** [comment]
implemented
