### ISSUE TITLE
Improve flashlight (2-part)

### ISSUE THREAD

**Issue by GL513** [sds100/KeyMapper#735]
If you have ever seen [torchie](https://play.google.com/store/apps/details?id=in.blogspot.anselmbros.torchie), they have a pretty cool setup. Luckily vibration is already built into Keymapper, but i wanted to do a little more with it.
It is already possible to turn on the flashlight, and then set a timeout, but it is hard for some new users. Possibly add a simple timeout feature so the flashlight can automatically turn on, and turn off.
Another thing i liked about torchie was that it had the option to use the screen as a "flashlight" it would be nice to see this built in to keymapper. I was also thinking, you could have a slider on the white screen, or nothing at all, but when you swipe it, it will adjust the system brightness either up or down. After the flashlight activity is exited, the app will return the brightness back to what it was, and also toggle auto brightness if previously on.
I think it would be super epic if we could do custom color screen lights as well, so we can add more warmth to the light, coolness, etc.
This might be a stretch, and i understand that you may reject this for now, but i think it would up the ratings as well because people would most likely switch from torchie to keymapper like i did a while ago.
🍉

**Comment by sds100** [comment]
yeah, this isn't going to happen 😂. does torchie allow you to trigger it from an app shortcut?
