### ISSUE TITLE
Window Reapearance

### ISSUE THREAD

**Issue by GL513** [sds100/KeyMapper#757]
Minor bug. This could probably be quickly fixed.
The window in Settings>Automatically change the keyboard>Choose devices appears twice, as shown [here](https://media.discordapp.net/attachments/836164219073331213/875869839779069962/Screen_Recording_20210813-183331_Key_Mapper_CI.mp4).
Mostly annoying, i wouldnt mind if this isnt fixed quickly.

Another thing, what if we just rename "Automatically change *the* keyboard" to "Automatically change keyboard" just to keep it shorter, and on some low-set DPI devices to remove the text wrap if there is any

**Comment by sds100** [comment]
yup will fix

**Comment by sds100** [comment]
isnt it more correct to use "the" though? that small removal shouldnt make much difference

**Comment by sds100** [comment]
fixed
