### ISSUE TITLE
Keymapper Crashed

### ISSUE THREAD

**Issue by Rexx16** [sds100/KeyMapper#758]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**

**Describe the bug**

**To Reproduce**

Upload a backup of your keymaps. (Follow the guide here.)[https://sds100.github.io/KeyMapper/user-guide/backup-restore]

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your  #problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T]
 - Android version: [e.g. Android 10]

**Additional context**
Keymapper crashed I cant use keymapper

**Comment by sds100** [comment]
no information given so will be impossible to fix
