### ISSUE TITLE
Opening the accessibility service settings doesn't work on some Android TVs

### ISSUE THREAD

**Issue by islam2hamy** [sds100/KeyMapper#780]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name if not a very quick fix.
- [x] write tests. put issue number in comment
- [x] prompt user to read tutorial in documentation that explains how to fix this
- [x] update documentation
- [x] squash and merge
- [x] delete branch

**Discord message link/email recipient**

**Describe the bug**
Couldn't give the app accessibility service permission

**To Reproduce**
Go to the accessibility service permission
Turn it on for this app
Go back
Go to the accessibility service permission again

Upload a backup of your keymaps. (Follow the guide here.)[https://sds100.github.io/KeyMapper/user-guide/backup-restore]

**Expected behavior**
accessibility service is enabled

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: mi tv stick
 - Android version:  Android 9

**Additional context**

**Comment by sds100** [comment]
can you reproduce this bug every time? even if you restart the TV?

**Comment by islam2hamy** [comment]
Yes

**Comment by sds100** [comment]
[keymapper-2.3.1-debug.zip](https://github.com/sds100/KeyMapper/files/7259060/keymapper-2.3.1-debug.zip)

Can you install this apk and see if it also has the issue. Also send a screen recording of the issue if you can. :)

**Comment by islam2hamy** [comment]
<a href="https://ibb.co/L9dNpXF"><img src="https://i.ibb.co/RQTjHkF/eb6955c8-7087-407c-9b89-e5af7d4a7be4.jpg" alt="eb6955c8-7087-407c-9b89-e5af7d4a7be4" border="0"></a>

**Comment by islam2hamy** [comment]
The same

**Comment by GL513** [comment]
what if you try using adb to write itself into the accessibility?
This person had a similar issue
https://www.reddit.com/r/AndroidTV/comments/it3xsx/unable_to_find_accessibility_services/g5c9yjv/

**Comment by sds100** [comment]
Oh, I misunderstood your issue. Yeah, that apk won't fix it. There isn't a way for Key Mapper to open the accessibility settings if they don't exist or the system doesn't allow apps to open them. I will make a more descriptive error message that redirects you to a tutorial on docs.keymapper.club. @GL513 Can you do this and make a pull request? It will go in the known-issues page.

**Comment by islam2hamy** [comment]
> what if you try using adb to write itself into the accessibility? This person had a similar issue https://www.reddit.com/r/AndroidTV/comments/it3xsx/unable_to_find_accessibility_services/g5c9yjv/

:)
It is work ! 
But i am sad because the netflix button couldn't be remapped

**Comment by sds100** [comment]
Yeah, some TV OEMs allow it and others don't. Pure luck 🤷‍♂️

**Comment by sds100** [comment]
fixed
