### ISSUE TITLE
I cannot record  a trigger

### ISSUE THREAD

**Issue by Infinitynukegems** [sds100/KeyMapper#802]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**

**Describe the bug**

**To Reproduce**

Upload a backup of your keymaps. [Follow the guide here.](https://sds100.github.io/KeyMapper/user-guide/backup-restore)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T]
 - Android version: [e.g. Android 10]

**Additional context**
Hello uhmmmm i saw keymapper and i really love keymapper but now i hate it because i cannot record a trigger plsss help me i really wanted to play
[key_mapper_report_20211015-204826.zip](https://github.com/sds100/KeyMapper/files/7353562/key_mapper_report_20211015-204826.zip)

**Comment by sds100** [comment]
Hello, please turn the accessibility service off and on. If that doesn't fix it then please send a screen recording.
