### ISSUE TITLE
Mouse-to-Touch simulation Required

### ISSUE THREAD

**Issue by unituniverse** [sds100/KeyMapper#812]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

There is already a function in KeyMapper to simulate touches. However it ask for a specific RCS x-y to do it. But what I ask for is if we can get a dynamic coordinate to do touch assigned with mouse/keyboard/D-Pad keys to do touches.
It will be very useful for Android simulated/virtualized platforms like VMware-workstation/ESX or VirtualBox. Until now there are only a few of specific-wares made by simulator-product and they can only be used within their products.

**Comment by sds100** [comment]
Hello, I'm not quite sure what you mean. Are you wanting Key Mapper to read where your mouse is pointing and then tap the screen in that location?

**Comment by unituniverse** [comment]
> Hello, I'm not quite sure what you mean. Are you wanting Key Mapper to read where your mouse is pointing and then tap the screen in that location?

Yes.
Maybe even more.
Now I'm wondering if the finger-dragging can be simulated with mouse...
I don't familiar with Kotlin so I can't provide anything useful advise about your code (I mean generally I prefer to figure it out by myself, However I can't for now /._.\ ).

**Comment by sds100** [comment]
Ah, unfortunately Android doesn't allow apps to do this (without root and hacky pieces of software) so this won't be possible.

**Comment by unituniverse** [comment]
> Ah, unfortunately Android doesn't allow apps to do this (without root and hacky pieces of software) so this won't be possible.

Sad. The getevent command needs root to work either.

> 
> * Doesn't allow them to track where the mouse is. The mouse should also do the same thing as finger dragging anyway so I doubt if Key Mapper fakes the input then it will also work.

I think so. :)

BTW many games only respond to touch events. Clicking or dragging mouse will trigger nothing during playing them.

**Comment by sds100** [comment]
Yeah, they probably filter inputs not from "real" fingers to prevent cheating etc. I'm going to close this because it won't be possible to implement
