### ISSUE TITLE
Apps aren't showing for selection

### ISSUE THREAD

**Issue by mizzunet** [sds100/KeyMapper#823]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**
mizzunet@protonmail.com

**Describe the bug**
No apps showing for selection for the actions like "Resume playback for an app"

**To Reproduce**
1. Add a key map
2. Get to Action tab and tap on 'Add'
3. Get to 'System' tab
4. Choose any action of 'Media' that is 'for an app'
5. See the list is empty to choose 

**Expected behavior**
List the apps installed, so I could select one

**Screenshots**
![image](https://user-images.githubusercontent.com/10193999/141287258-17a30785-00ab-4861-bd86-0d60ebc675e9.png)

**Smartphone (please complete the following information):**
 - Device:OnePlus 5
 - Android version: Android 11, LineageOS

**Additional context**
I wanted to play for AntennaPod

**Comment by GL513** [comment]
1) have you tried... restarting the device, and/or force killing the app and reopening it?

2) because you are running a custom ROM, this might break things. If you have something to restrict apps from seeing other apps, make sure that keymapper is enabled so it can see other applications, and that it has the permission `QUERY_ALL_PACKAGES` if it doesn't already.

**Comment by mizzunet** [comment]
@GL513 
1. Yes
2. I think this permission has been allowed for Key Mapper as it can list all apps under 'App' tab of Actions which is to opening action

**Comment by sds100** [comment]
Hi! This might be a bug. Can you try the latest testing build to see if it also has the issue. Read this guide on how to get these builds https://docs.keymapper.club/contributing/#becoming-a-tester

**Comment by mizzunet** [comment]
@sds100 Sure

**Comment by sds100** [comment]
It is just http.

**Comment by sds100** [comment]
Just the alpha builds

**Comment by mizzunet** [comment]
@sds100 Fortunately, in 2.4.0 list of apps shown
Thank you :heart:

**Comment by sds100** [comment]
okay, cool. ill close this now ;)

**Comment by mizzunet** [comment]
BTW, there weren't `#testing-builds` in discord
![image](https://user-images.githubusercontent.com/10193999/141324234-3cd9394b-4aa1-4fc4-ac4d-479c6efb8ae9.png)

**Comment by GL513** [comment]
> BTW, there weren't `#testing-builds` in discord
Go to Rules and do !agree

**Comment by mizzunet** [comment]
@GL513 cool
