### ISSUE TITLE
Actions: Shell script

### ISSUE THREAD

**Issue by mizzunet** [sds100/KeyMapper#824]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

It'd be quite useful to have an action for running shell commands

**Comment by GL513** [comment]
> **Developer TODO (don't remove)**
> 
> * [ ]  create new branch. put issue number at start of name
> * [ ]  update documentation
> * [ ]  squash and merge
> * [ ]  delete branch
> 
> It'd be quite useful to have an action for running shell commands

please close this issue and refer to #782 and #661. Please comment there if you are looking for something, or want to ask a question related to the topic.

**Comment by mizzunet** [comment]
Oops
