### ISSUE TITLE
3rd-party Gradle plug-ins may be the cause

### ISSUE THREAD

**Issue by bellalzohir** [sds100/KeyMapper#83]
I did download the project but I can't start it case this problem 

(3rd-party Gradle plug-ins may be the cause) and I want just to convert it to Java to extend it 

thanx in advance

**Comment by sds100** [comment]
Hi. I'll look into it! 🙂

**Comment by sds100** [comment]
Building and running the project worked for me. When you download the project as a zip (not cloning it) and extract it, there is a  "KeyMapper-develop" folder inside the extracted "KeyMapper-develop" folder. When you open the project in Android Studio, make sure you open the folder inside. At first I didnt open the folder inside and it didnt work. Also make sure you have downloaded the Kotlin and Gradle plugins. 
![image](https://user-images.githubusercontent.com/16245954/52444593-b0ff9b00-2b20-11e9-84f5-c69542972223.png)

🙂
