### ISSUE TITLE
Asb commands to leave out of  battery optimisation and enable accesibility service

### ISSUE THREAD

**Issue by Droidphilev** [sds100/KeyMapper#836]
Hello all,

Sorry to contact you this way. I woild like yo use KeyMapper on a special device that has both "battery optimisation" and "accessibility services" hidden from settings. They are still in the OS though (nougat). Would you mind letting me know both commands for adb please?

Kind regards,
Phil

**Comment by sds100** [comment]
Hi, it is fine to contact this way. I won't forget to reply to this ;). I have written a guide on how to enable the accessibility service with ADB here https://docs.keymapper.club/user-guide/adb-permissions/#enabling-the-accessibility-service

**Comment by sds100** [comment]
You can use this command to disable battery optimisation ```adb shell dumpsys deviceidle whitelist "+io.github.sds100.keymapper.debug"```

**Comment by Droidphilev** [comment]
Thank you kindly!
