### ISSUE TITLE
Toggle airplane mode does not work

### ISSUE THREAD

**Issue by Soukyuu** [sds100/KeyMapper#854]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Describe the bug**
Setting the action to "Toggle airplane mode" has no effect, root is enabled. "Activate airplane mode" works

**To Reproduce**
- set trigger to long press
- set action to "toggle airplane mode"
- set options to vibrate
- trigger the action

**Expected behavior**
- the phone vibrating
- the phone toggling the airplane mode

**Actual behavior**
- the phone vibrates
- airplane mode does not change

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi Mix 3
 - Android version: 11r45

**Comment by sds100** [comment]
thank you for reporting this! I've just fixed it. You'll be able to download the fixed apk from this GitHub Actions run https://github.com/sds100/KeyMapper/actions/runs/1573218989

**Comment by Soukyuu** [comment]
That was fast - thank you!
