### ISSUE TITLE
App doesn't show in Android TV Play Store

### ISSUE THREAD

**Issue by TxI5** [sds100/KeyMapper#862]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**

**Describe the bug**
I can't find the app in the Play Store on Android TV

**To Reproduce**
Search play store from Android TV

**Expected behavior**
The app to be in the playstore

**Smartphone (please complete the following information):**
 - Device: Android TV
 - Android version: 9

**Comment by sds100** [comment]
Hi, this is a known "issue" because I haven't optimised this app for Android TV yet. You can see all the things that I need to do here https://github.com/sds100/KeyMapper/projects/13
