### ISSUE TITLE
Non-portrait constraint prevents trigger

### ISSUE THREAD

**Issue by ViktorWalter** [sds100/KeyMapper#869]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**
viktor.walter@disroot.org

**Describe the bug**
(this doubles as steps to reproduce)

I have made two separate triggers for the OpenCamera app which each tap on on-screen trigger button upon hardware button press. They are essentially identical to each other, with the difference between them being that one is constrained to execute when Portrait mode is active and the other when Landscape mode is active. This is to account for the fact that between these two modes, the pixel coordinates of the on-screen trigger button change.
The portrait mode action triggers as expected, while the landscape mode never triggers. I have tried disabling the portrait mode trigger to see if it doesn't mask the other trigger, but without success. It seems that for some reason, having the landscape mode as a constraint entirely prevents the trigger from executing. I have verified this by activating the on-screen message, where it did not show only for the landscape-constrained trigger.

**To Reproduce**
See above.

Upload a backup of your keymaps. 
[here](https://upload.disroot.org/r/8KU1VM0Z#cbsEt/E++ATneU5JnIGhJ03j2xGf0KLcq0YUWkESVXc=)

**Expected behavior**
Two triggers differing only in their screen orientation constraint should both work in these respective screen orientations.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Doogee S60
 - Android version: 8.0/Oreo

**Additional context**
N/A

**Comment by ViktorWalter** [comment]
Sorry to be closing it so soon - writing it down made me realize what the issue was - I have system-wide mapped the hardware button in question to the right arrow key (by rewriting the keymap file in the system to prevent it from always running the camera app, long story short). However, in Landscape mode, the Right arrow key is interpreted by Android as Up/Down as the case may be. Re-recording the trigger for the landscape mode in the actual landscape mode showed it as triggered by Up and now it works.

**Comment by sds100** [comment]
Glad that you fixed it! And thank you for following the issue template. 🙂
