### ISSUE TITLE
Feature Request: screen rotate as a trigger

### ISSUE THREAD

**Issue by sudomain** [sds100/KeyMapper#871]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

This might be out if scope for the app, but I figured it might be worth asking. I'd like to have screen rotation as a trigger for one of my maps. I realize this isn't a "key" to map, but I'd find it really useful for a project: What I'm hoping to do is:
1. When screen rotates AND my VNC client app is in the foreground (only KeyMapper offers the second condition as far as FDroid automation apps are concerned)
2. Start a Termux shortcut to SSH into my device running the VNC server
3. Run a `xrandr` command to change the dimensions of a virtual desktop to that of the newly rotated device i.e. rotating the Android device from portrait (720x1280) to landscape (1280x720) will change the geometry of the desktop using `xrandr`

I can make 2 + 3 happen, but 1 would require KeyMapper detecting a screen rotation. I use FDroid as my main app store and KeyMapper seems to be the only automation app on it that has conditions to detect which app is in the foreground.

**Comment by GL513** [comment]
Just a simple question, have you asked anyone if they know how to do this with something else already in any official termux chatroom?

**Comment by sds100** [comment]
Yeah, I think this is out-of-scope of this app because that would make it an automation app like Tasker or Automate. You should find a FOSS automation app that can trigger Key Mapper key maps with an Intent. 🙂

**Comment by sudomain** [comment]
Hi all,

I found a work around- KeyMapper actions of
1. Toggle autorotation
2. Cycle through through rotations
3. App shortcut - Termux shortcut

For now I don't have a major use of my volume keys when using my VNC client, so I'll use those as a trigger, but maybe I'll control it with a Termux notification that sends intents to KeyMapper.
