### ISSUE TITLE
Keymapper dead?

### ISSUE THREAD

**Issue by Z3tr23** [sds100/KeyMapper#872]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**

**Describe the bug**

**To Reproduce**

Upload a backup of your keymaps. [Follow the guide here.](https://sds100.github.io/KeyMapper/user-guide/backup-restore)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T]
 - Android version: [e.g. Android 10]

**Additional context**

**Comment by GL513** [comment]
Hey, can you please provide more detail for @sds100 or close the issue? Thanks.

**Comment by sds100** [comment]
Key Mapper isn't officially dead but I've started university, which means I don't have much time to work on it.
