### ISSUE TITLE
لا يعمل

### ISSUE THREAD

**Issue by rony6712** [sds100/KeyMapper#880]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

**Discord message link/email recipient**

**Describe the bug**

**To Reproduce**

Upload a backup of your keymaps. [Follow the guide here.](https://sds100.github.io/KeyMapper/user-guide/backup-restore)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 6T]
 - Android version: [e.g. Android 10]

**Additional context**

**Comment by GL513** [comment]
Hi, we try to keep all of the issues in english only, so please use google translate or something close to it if you absolutely need it. Also, please close your issue or provide more details, thanks.
